//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.13 at 02:57:41 PM WIB 
//


package id.co.qualitas.domain.webservice.stockoem;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="P_LGORT" type="{urn:sap-com:document:sap:rfc:functions}char4" minOccurs="0"/&gt;
 *         &lt;element name="P_MATNR" type="{urn:sap-com:document:sap:rfc:functions}char18" minOccurs="0"/&gt;
 *         &lt;element name="P_MTART" type="{urn:sap-com:document:sap:rfc:functions}char4" minOccurs="0"/&gt;
 *         &lt;element name="P_WERKS" type="{urn:sap-com:document:sap:rfc:functions}char4" minOccurs="0"/&gt;
 *         &lt;element name="RESULT" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZTY_WB_OEM"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plgort",
    "pmatnr",
    "pmtart",
    "pwerks",
    "result"
})
@XmlRootElement(name = "ZFM_WB_STOCK_OEM")
public class ZFMWBSTOCKOEM {

    @XmlElement(name = "P_LGORT")
    protected String plgort;
    @XmlElement(name = "P_MATNR")
    protected String pmatnr;
    @XmlElement(name = "P_MTART")
    protected String pmtart;
    @XmlElement(name = "P_WERKS")
    protected String pwerks;
    @XmlElement(name = "RESULT", required = true)
    protected TABLEOFZTYWBOEM result;

    /**
     * Gets the value of the plgort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLGORT() {
        return plgort;
    }

    /**
     * Sets the value of the plgort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLGORT(String value) {
        this.plgort = value;
    }

    /**
     * Gets the value of the pmatnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPMATNR() {
        return pmatnr;
    }

    /**
     * Sets the value of the pmatnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPMATNR(String value) {
        this.pmatnr = value;
    }

    /**
     * Gets the value of the pmtart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPMTART() {
        return pmtart;
    }

    /**
     * Sets the value of the pmtart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPMTART(String value) {
        this.pmtart = value;
    }

    /**
     * Gets the value of the pwerks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPWERKS() {
        return pwerks;
    }

    /**
     * Sets the value of the pwerks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPWERKS(String value) {
        this.pwerks = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZTYWBOEM }
     *     
     */
    public TABLEOFZTYWBOEM getRESULT() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZTYWBOEM }
     *     
     */
    public void setRESULT(TABLEOFZTYWBOEM value) {
        this.result = value;
    }

}
