//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.13 at 02:57:41 PM WIB 
//


package id.co.qualitas.domain.webservice.stockoem;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZTY_WB_OEM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZTY_WB_OEM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WERKS" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="LGORT" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="LIFNR" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="MATNR" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="MAKTX" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="MTART" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="CHARG" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="CLABS" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="CINSM" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="CSPEM" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="LBLAB" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="MEINS" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="HSDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="VFDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="LWEDT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZTY_WB_OEM", propOrder = {
    "werks",
    "lgort",
    "lifnr",
    "matnr",
    "maktx",
    "mtart",
    "charg",
    "clabs",
    "cinsm",
    "cspem",
    "lblab",
    "meins",
    "hsdat",
    "vfdat",
    "lwedt"
})
public class ZTYWBOEM {

    @XmlElement(name = "WERKS", required = true)
    protected String werks;
    @XmlElement(name = "LGORT", required = true)
    protected String lgort;
    @XmlElement(name = "LIFNR", required = true)
    protected String lifnr;
    @XmlElement(name = "MATNR", required = true)
    protected String matnr;
    @XmlElement(name = "MAKTX", required = true)
    protected String maktx;
    @XmlElement(name = "MTART", required = true)
    protected String mtart;
    @XmlElement(name = "CHARG", required = true)
    protected String charg;
    @XmlElement(name = "CLABS", required = true)
    protected BigDecimal clabs;
    @XmlElement(name = "CINSM", required = true)
    protected BigDecimal cinsm;
    @XmlElement(name = "CSPEM", required = true)
    protected BigDecimal cspem;
    @XmlElement(name = "LBLAB", required = true)
    protected BigDecimal lblab;
    @XmlElement(name = "MEINS", required = true)
    protected String meins;
    @XmlElement(name = "HSDAT", required = true)
    protected String hsdat;
    @XmlElement(name = "VFDAT", required = true)
    protected String vfdat;
    @XmlElement(name = "LWEDT", required = true)
    protected String lwedt;

    /**
     * Gets the value of the werks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWERKS() {
        return werks;
    }

    /**
     * Sets the value of the werks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWERKS(String value) {
        this.werks = value;
    }

    /**
     * Gets the value of the lgort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLGORT() {
        return lgort;
    }

    /**
     * Sets the value of the lgort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLGORT(String value) {
        this.lgort = value;
    }

    /**
     * Gets the value of the lifnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIFNR() {
        return lifnr;
    }

    /**
     * Sets the value of the lifnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIFNR(String value) {
        this.lifnr = value;
    }

    /**
     * Gets the value of the matnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATNR() {
        return matnr;
    }

    /**
     * Sets the value of the matnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATNR(String value) {
        this.matnr = value;
    }

    /**
     * Gets the value of the maktx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAKTX() {
        return maktx;
    }

    /**
     * Sets the value of the maktx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAKTX(String value) {
        this.maktx = value;
    }

    /**
     * Gets the value of the mtart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTART() {
        return mtart;
    }

    /**
     * Sets the value of the mtart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTART(String value) {
        this.mtart = value;
    }

    /**
     * Gets the value of the charg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHARG() {
        return charg;
    }

    /**
     * Sets the value of the charg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHARG(String value) {
        this.charg = value;
    }

    /**
     * Gets the value of the clabs property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCLABS() {
        return clabs;
    }

    /**
     * Sets the value of the clabs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCLABS(BigDecimal value) {
        this.clabs = value;
    }

    /**
     * Gets the value of the cinsm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCINSM() {
        return cinsm;
    }

    /**
     * Sets the value of the cinsm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCINSM(BigDecimal value) {
        this.cinsm = value;
    }

    /**
     * Gets the value of the cspem property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCSPEM() {
        return cspem;
    }

    /**
     * Sets the value of the cspem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCSPEM(BigDecimal value) {
        this.cspem = value;
    }

    /**
     * Gets the value of the lblab property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLBLAB() {
        return lblab;
    }

    /**
     * Sets the value of the lblab property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLBLAB(BigDecimal value) {
        this.lblab = value;
    }

    /**
     * Gets the value of the meins property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEINS() {
        return meins;
    }

    /**
     * Sets the value of the meins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEINS(String value) {
        this.meins = value;
    }

    /**
     * Gets the value of the hsdat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSDAT() {
        return hsdat;
    }

    /**
     * Sets the value of the hsdat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSDAT(String value) {
        this.hsdat = value;
    }

    /**
     * Gets the value of the vfdat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVFDAT() {
        return vfdat;
    }

    /**
     * Sets the value of the vfdat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVFDAT(String value) {
        this.vfdat = value;
    }

    /**
     * Gets the value of the lwedt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLWEDT() {
        return lwedt;
    }

    /**
     * Sets the value of the lwedt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLWEDT(String value) {
        this.lwedt = value;
    }

}
