//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 04:19:12 PM WIB 
//


package id.co.qualitas.domain.webservice.goodsmvt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bapi2017GmSerialnumber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bapi2017GmSerialnumber"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MatdocItm" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="Serialno" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="Uii" type="{urn:sap-com:document:sap:rfc:functions}char72"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bapi2017GmSerialnumber", propOrder = {
    "matdocItm",
    "serialno",
    "uii"
})
public class Bapi2017GmSerialnumber {

    @XmlElement(name = "MatdocItm", required = true)
    protected String matdocItm;
    @XmlElement(name = "Serialno", required = true)
    protected String serialno;
    @XmlElement(name = "Uii", required = true)
    protected String uii;

    /**
     * Gets the value of the matdocItm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatdocItm() {
        return matdocItm;
    }

    /**
     * Sets the value of the matdocItm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatdocItm(String value) {
        this.matdocItm = value;
    }

    /**
     * Gets the value of the serialno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialno() {
        return serialno;
    }

    /**
     * Sets the value of the serialno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialno(String value) {
        this.serialno = value;
    }

    /**
     * Gets the value of the uii property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUii() {
        return uii;
    }

    /**
     * Sets the value of the uii property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUii(String value) {
        this.uii = value;
    }

}
