//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 04:19:12 PM WIB 
//


package id.co.qualitas.domain.webservice.goodsmvt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bapi2017GmHead01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bapi2017GmHead01"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PstngDate" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="DocDate" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="RefDocNo" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="BillOfLading" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="GrGiSlipNo" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="PrUname" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="HeaderTxt" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *         &lt;element name="VerGrGiSlip" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="VerGrGiSlipx" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ExtWms" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="RefDocNoLong" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="BillOfLadingLong" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="BarCode" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bapi2017GmHead01", propOrder = {
    "pstngDate",
    "docDate",
    "refDocNo",
    "billOfLading",
    "grGiSlipNo",
    "prUname",
    "headerTxt",
    "verGrGiSlip",
    "verGrGiSlipx",
    "extWms",
    "refDocNoLong",
    "billOfLadingLong",
    "barCode"
})
public class Bapi2017GmHead01 {

    @XmlElement(name = "PstngDate", required = true)
    protected String pstngDate;
    @XmlElement(name = "DocDate", required = true)
    protected String docDate;
    @XmlElement(name = "RefDocNo", required = true)
    protected String refDocNo;
    @XmlElement(name = "BillOfLading", required = true)
    protected String billOfLading;
    @XmlElement(name = "GrGiSlipNo", required = true)
    protected String grGiSlipNo;
    @XmlElement(name = "PrUname", required = true)
    protected String prUname;
    @XmlElement(name = "HeaderTxt", required = true)
    protected String headerTxt;
    @XmlElement(name = "VerGrGiSlip", required = true)
    protected String verGrGiSlip;
    @XmlElement(name = "VerGrGiSlipx", required = true)
    protected String verGrGiSlipx;
    @XmlElement(name = "ExtWms", required = true)
    protected String extWms;
    @XmlElement(name = "RefDocNoLong", required = true)
    protected String refDocNoLong;
    @XmlElement(name = "BillOfLadingLong", required = true)
    protected String billOfLadingLong;
    @XmlElement(name = "BarCode", required = true)
    protected String barCode;

    /**
     * Gets the value of the pstngDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPstngDate() {
        return pstngDate;
    }

    /**
     * Sets the value of the pstngDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPstngDate(String value) {
        this.pstngDate = value;
    }

    /**
     * Gets the value of the docDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocDate() {
        return docDate;
    }

    /**
     * Sets the value of the docDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocDate(String value) {
        this.docDate = value;
    }

    /**
     * Gets the value of the refDocNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDocNo() {
        return refDocNo;
    }

    /**
     * Sets the value of the refDocNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDocNo(String value) {
        this.refDocNo = value;
    }

    /**
     * Gets the value of the billOfLading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillOfLading() {
        return billOfLading;
    }

    /**
     * Sets the value of the billOfLading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillOfLading(String value) {
        this.billOfLading = value;
    }

    /**
     * Gets the value of the grGiSlipNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrGiSlipNo() {
        return grGiSlipNo;
    }

    /**
     * Sets the value of the grGiSlipNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrGiSlipNo(String value) {
        this.grGiSlipNo = value;
    }

    /**
     * Gets the value of the prUname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrUname() {
        return prUname;
    }

    /**
     * Sets the value of the prUname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrUname(String value) {
        this.prUname = value;
    }

    /**
     * Gets the value of the headerTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderTxt() {
        return headerTxt;
    }

    /**
     * Sets the value of the headerTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderTxt(String value) {
        this.headerTxt = value;
    }

    /**
     * Gets the value of the verGrGiSlip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerGrGiSlip() {
        return verGrGiSlip;
    }

    /**
     * Sets the value of the verGrGiSlip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerGrGiSlip(String value) {
        this.verGrGiSlip = value;
    }

    /**
     * Gets the value of the verGrGiSlipx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerGrGiSlipx() {
        return verGrGiSlipx;
    }

    /**
     * Sets the value of the verGrGiSlipx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerGrGiSlipx(String value) {
        this.verGrGiSlipx = value;
    }

    /**
     * Gets the value of the extWms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtWms() {
        return extWms;
    }

    /**
     * Sets the value of the extWms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtWms(String value) {
        this.extWms = value;
    }

    /**
     * Gets the value of the refDocNoLong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDocNoLong() {
        return refDocNoLong;
    }

    /**
     * Sets the value of the refDocNoLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDocNoLong(String value) {
        this.refDocNoLong = value;
    }

    /**
     * Gets the value of the billOfLadingLong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillOfLadingLong() {
        return billOfLadingLong;
    }

    /**
     * Sets the value of the billOfLadingLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillOfLadingLong(String value) {
        this.billOfLadingLong = value;
    }

    /**
     * Gets the value of the barCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * Sets the value of the barCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarCode(String value) {
        this.barCode = value;
    }

}
