//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 04:19:12 PM WIB 
//


package id.co.qualitas.domain.webservice.goodsmvt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bapiparex complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bapiparex"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Structure" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="Valuepart1" type="{urn:sap-com:document:sap:rfc:functions}char240"/&gt;
 *         &lt;element name="Valuepart2" type="{urn:sap-com:document:sap:rfc:functions}char240"/&gt;
 *         &lt;element name="Valuepart3" type="{urn:sap-com:document:sap:rfc:functions}char240"/&gt;
 *         &lt;element name="Valuepart4" type="{urn:sap-com:document:sap:rfc:functions}char240"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bapiparex", propOrder = {
    "structure",
    "valuepart1",
    "valuepart2",
    "valuepart3",
    "valuepart4"
})
public class Bapiparex {

    @XmlElement(name = "Structure", required = true)
    protected String structure;
    @XmlElement(name = "Valuepart1", required = true)
    protected String valuepart1;
    @XmlElement(name = "Valuepart2", required = true)
    protected String valuepart2;
    @XmlElement(name = "Valuepart3", required = true)
    protected String valuepart3;
    @XmlElement(name = "Valuepart4", required = true)
    protected String valuepart4;

    /**
     * Gets the value of the structure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStructure() {
        return structure;
    }

    /**
     * Sets the value of the structure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStructure(String value) {
        this.structure = value;
    }

    /**
     * Gets the value of the valuepart1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuepart1() {
        return valuepart1;
    }

    /**
     * Sets the value of the valuepart1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuepart1(String value) {
        this.valuepart1 = value;
    }

    /**
     * Gets the value of the valuepart2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuepart2() {
        return valuepart2;
    }

    /**
     * Sets the value of the valuepart2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuepart2(String value) {
        this.valuepart2 = value;
    }

    /**
     * Gets the value of the valuepart3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuepart3() {
        return valuepart3;
    }

    /**
     * Sets the value of the valuepart3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuepart3(String value) {
        this.valuepart3 = value;
    }

    /**
     * Gets the value of the valuepart4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuepart4() {
        return valuepart4;
    }

    /**
     * Sets the value of the valuepart4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuepart4(String value) {
        this.valuepart4 = value;
    }

}
