//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 04:19:12 PM WIB 
//


package id.co.qualitas.domain.webservice.goodsmvt;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bapi2017GmItemCreate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bapi2017GmItemCreate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Material" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="Plant" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="StgeLoc" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="Batch" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="MoveType" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="StckType" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="SpecStock" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="Vendor" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="Customer" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="SalesOrd" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="SOrdItem" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="SchedLine" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="ValType" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="EntryQnt" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="EntryUom" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="EntryUomIso" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="PoPrQnt" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="OrderprUn" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="OrderprUnIso" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="PoNumber" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="PoItem" type="{urn:sap-com:document:sap:rfc:functions}numeric5"/&gt;
 *         &lt;element name="Shipping" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="CompShip" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="NoMoreGr" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ItemText" type="{urn:sap-com:document:sap:rfc:functions}char50"/&gt;
 *         &lt;element name="GrRcpt" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="UnloadPt" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *         &lt;element name="Costcenter" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="Orderid" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="OrderItno" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="CalcMotive" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="AssetNo" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="SubNumber" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="ReservNo" type="{urn:sap-com:document:sap:rfc:functions}numeric10"/&gt;
 *         &lt;element name="ResItem" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="ResType" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="Withdrawn" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="MoveMat" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="MovePlant" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="MoveStloc" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="MoveBatch" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="MoveValType" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="MvtInd" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="MoveReas" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="RlEstKey" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="RefDate" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="CostObj" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="ProfitSegmNo" type="{urn:sap-com:document:sap:rfc:functions}numeric10"/&gt;
 *         &lt;element name="ProfitCtr" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="WbsElem" type="{urn:sap-com:document:sap:rfc:functions}char24"/&gt;
 *         &lt;element name="Network" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="Activity" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="PartAcct" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="AmountLc" type="{urn:sap-com:document:sap:rfc:functions}decimal23.4"/&gt;
 *         &lt;element name="AmountSv" type="{urn:sap-com:document:sap:rfc:functions}decimal23.4"/&gt;
 *         &lt;element name="RefDocYr" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="RefDoc" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="RefDocIt" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="Expirydate" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="ProdDate" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="Fund" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="FundsCtr" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="CmmtItem" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *         &lt;element name="ValSalesOrd" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="ValSOrdItem" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="ValWbsElem" type="{urn:sap-com:document:sap:rfc:functions}char24"/&gt;
 *         &lt;element name="GlAccount" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="IndProposeQuanx" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="Xstob" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="EanUpc" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="DelivNumbToSearch" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="DelivItemToSearch" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="SerialnoAutoNumberassignment" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="Vendrbatch" type="{urn:sap-com:document:sap:rfc:functions}char15"/&gt;
 *         &lt;element name="StgeType" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="StgeBin" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="SuPlStck1" type="{urn:sap-com:document:sap:rfc:functions}decimal3.0"/&gt;
 *         &lt;element name="StUnQtyy1" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="StUnQtyy1Iso" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="Unittype1" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="SuPlStck2" type="{urn:sap-com:document:sap:rfc:functions}decimal3.0"/&gt;
 *         &lt;element name="StUnQtyy2" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="StUnQtyy2Iso" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="Unittype2" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="StgeTypePc" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="StgeBinPc" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="NoPstChgnt" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="GrNumber" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="StgeTypeSt" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="StgeBinSt" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="MatdocTrCancel" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="MatitemTrCancel" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="MatyearTrCancel" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="NoTransferReq" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="CoBusproc" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="Acttype" type="{urn:sap-com:document:sap:rfc:functions}char6"/&gt;
 *         &lt;element name="SupplVend" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="MaterialExternal" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="MaterialGuid" type="{urn:sap-com:document:sap:rfc:functions}char32"/&gt;
 *         &lt;element name="MaterialVersion" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="MoveMatExternal" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="MoveMatGuid" type="{urn:sap-com:document:sap:rfc:functions}char32"/&gt;
 *         &lt;element name="MoveMatVersion" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="FuncArea" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="TrPartBa" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="ParCompco" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="DelivNumb" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="DelivItem" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="NbSlips" type="{urn:sap-com:document:sap:rfc:functions}numeric3"/&gt;
 *         &lt;element name="NbSlipsx" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="GrRcptx" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="UnloadPtx" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="SpecMvmt" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="GrantNbr" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="CmmtItemLong" type="{urn:sap-com:document:sap:rfc:functions}char24"/&gt;
 *         &lt;element name="FuncAreaLong" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="LineId" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="ParentId" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="LineDepth" type="{urn:sap-com:document:sap:rfc:functions}numeric2"/&gt;
 *         &lt;element name="Quantity" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="BaseUom" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="Longnum" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="BudgetPeriod" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bapi2017GmItemCreate", propOrder = {
    "material",
    "plant",
    "stgeLoc",
    "batch",
    "moveType",
    "stckType",
    "specStock",
    "vendor",
    "customer",
    "salesOrd",
    "sOrdItem",
    "schedLine",
    "valType",
    "entryQnt",
    "entryUom",
    "entryUomIso",
    "poPrQnt",
    "orderprUn",
    "orderprUnIso",
    "poNumber",
    "poItem",
    "shipping",
    "compShip",
    "noMoreGr",
    "itemText",
    "grRcpt",
    "unloadPt",
    "costcenter",
    "orderid",
    "orderItno",
    "calcMotive",
    "assetNo",
    "subNumber",
    "reservNo",
    "resItem",
    "resType",
    "withdrawn",
    "moveMat",
    "movePlant",
    "moveStloc",
    "moveBatch",
    "moveValType",
    "mvtInd",
    "moveReas",
    "rlEstKey",
    "refDate",
    "costObj",
    "profitSegmNo",
    "profitCtr",
    "wbsElem",
    "network",
    "activity",
    "partAcct",
    "amountLc",
    "amountSv",
    "refDocYr",
    "refDoc",
    "refDocIt",
    "expirydate",
    "prodDate",
    "fund",
    "fundsCtr",
    "cmmtItem",
    "valSalesOrd",
    "valSOrdItem",
    "valWbsElem",
    "glAccount",
    "indProposeQuanx",
    "xstob",
    "eanUpc",
    "delivNumbToSearch",
    "delivItemToSearch",
    "serialnoAutoNumberassignment",
    "vendrbatch",
    "stgeType",
    "stgeBin",
    "suPlStck1",
    "stUnQtyy1",
    "stUnQtyy1Iso",
    "unittype1",
    "suPlStck2",
    "stUnQtyy2",
    "stUnQtyy2Iso",
    "unittype2",
    "stgeTypePc",
    "stgeBinPc",
    "noPstChgnt",
    "grNumber",
    "stgeTypeSt",
    "stgeBinSt",
    "matdocTrCancel",
    "matitemTrCancel",
    "matyearTrCancel",
    "noTransferReq",
    "coBusproc",
    "acttype",
    "supplVend",
    "materialExternal",
    "materialGuid",
    "materialVersion",
    "moveMatExternal",
    "moveMatGuid",
    "moveMatVersion",
    "funcArea",
    "trPartBa",
    "parCompco",
    "delivNumb",
    "delivItem",
    "nbSlips",
    "nbSlipsx",
    "grRcptx",
    "unloadPtx",
    "specMvmt",
    "grantNbr",
    "cmmtItemLong",
    "funcAreaLong",
    "lineId",
    "parentId",
    "lineDepth",
    "quantity",
    "baseUom",
    "longnum",
    "budgetPeriod"
})
public class Bapi2017GmItemCreate {

    @XmlElement(name = "Material", required = true)
    protected String material;
    @XmlElement(name = "Plant", required = true)
    protected String plant;
    @XmlElement(name = "StgeLoc", required = true)
    protected String stgeLoc;
    @XmlElement(name = "Batch", required = true)
    protected String batch;
    @XmlElement(name = "MoveType", required = true)
    protected String moveType;
    @XmlElement(name = "StckType", required = true)
    protected String stckType;
    @XmlElement(name = "SpecStock", required = true)
    protected String specStock;
    @XmlElement(name = "Vendor", required = true)
    protected String vendor;
    @XmlElement(name = "Customer", required = true)
    protected String customer;
    @XmlElement(name = "SalesOrd", required = true)
    protected String salesOrd;
    @XmlElement(name = "SOrdItem", required = true)
    protected String sOrdItem;
    @XmlElement(name = "SchedLine", required = true)
    protected String schedLine;
    @XmlElement(name = "ValType", required = true)
    protected String valType;
    @XmlElement(name = "EntryQnt", required = true)
    protected BigDecimal entryQnt;
    @XmlElement(name = "EntryUom", required = true)
    protected String entryUom;
    @XmlElement(name = "EntryUomIso", required = true)
    protected String entryUomIso;
    @XmlElement(name = "PoPrQnt", required = true)
    protected BigDecimal poPrQnt;
    @XmlElement(name = "OrderprUn", required = true)
    protected String orderprUn;
    @XmlElement(name = "OrderprUnIso", required = true)
    protected String orderprUnIso;
    @XmlElement(name = "PoNumber", required = true)
    protected String poNumber;
    @XmlElement(name = "PoItem", required = true)
    protected String poItem;
    @XmlElement(name = "Shipping", required = true)
    protected String shipping;
    @XmlElement(name = "CompShip", required = true)
    protected String compShip;
    @XmlElement(name = "NoMoreGr", required = true)
    protected String noMoreGr;
    @XmlElement(name = "ItemText", required = true)
    protected String itemText;
    @XmlElement(name = "GrRcpt", required = true)
    protected String grRcpt;
    @XmlElement(name = "UnloadPt", required = true)
    protected String unloadPt;
    @XmlElement(name = "Costcenter", required = true)
    protected String costcenter;
    @XmlElement(name = "Orderid", required = true)
    protected String orderid;
    @XmlElement(name = "OrderItno", required = true)
    protected String orderItno;
    @XmlElement(name = "CalcMotive", required = true)
    protected String calcMotive;
    @XmlElement(name = "AssetNo", required = true)
    protected String assetNo;
    @XmlElement(name = "SubNumber", required = true)
    protected String subNumber;
    @XmlElement(name = "ReservNo", required = true)
    protected String reservNo;
    @XmlElement(name = "ResItem", required = true)
    protected String resItem;
    @XmlElement(name = "ResType", required = true)
    protected String resType;
    @XmlElement(name = "Withdrawn", required = true)
    protected String withdrawn;
    @XmlElement(name = "MoveMat", required = true)
    protected String moveMat;
    @XmlElement(name = "MovePlant", required = true)
    protected String movePlant;
    @XmlElement(name = "MoveStloc", required = true)
    protected String moveStloc;
    @XmlElement(name = "MoveBatch", required = true)
    protected String moveBatch;
    @XmlElement(name = "MoveValType", required = true)
    protected String moveValType;
    @XmlElement(name = "MvtInd", required = true)
    protected String mvtInd;
    @XmlElement(name = "MoveReas", required = true)
    protected String moveReas;
    @XmlElement(name = "RlEstKey", required = true)
    protected String rlEstKey;
    @XmlElement(name = "RefDate", required = true)
    protected String refDate;
    @XmlElement(name = "CostObj", required = true)
    protected String costObj;
    @XmlElement(name = "ProfitSegmNo", required = true)
    protected String profitSegmNo;
    @XmlElement(name = "ProfitCtr", required = true)
    protected String profitCtr;
    @XmlElement(name = "WbsElem", required = true)
    protected String wbsElem;
    @XmlElement(name = "Network", required = true)
    protected String network;
    @XmlElement(name = "Activity", required = true)
    protected String activity;
    @XmlElement(name = "PartAcct", required = true)
    protected String partAcct;
    @XmlElement(name = "AmountLc", required = true)
    protected BigDecimal amountLc;
    @XmlElement(name = "AmountSv", required = true)
    protected BigDecimal amountSv;
    @XmlElement(name = "RefDocYr", required = true)
    protected String refDocYr;
    @XmlElement(name = "RefDoc", required = true)
    protected String refDoc;
    @XmlElement(name = "RefDocIt", required = true)
    protected String refDocIt;
    @XmlElement(name = "Expirydate", required = true)
    protected String expirydate;
    @XmlElement(name = "ProdDate", required = true)
    protected String prodDate;
    @XmlElement(name = "Fund", required = true)
    protected String fund;
    @XmlElement(name = "FundsCtr", required = true)
    protected String fundsCtr;
    @XmlElement(name = "CmmtItem", required = true)
    protected String cmmtItem;
    @XmlElement(name = "ValSalesOrd", required = true)
    protected String valSalesOrd;
    @XmlElement(name = "ValSOrdItem", required = true)
    protected String valSOrdItem;
    @XmlElement(name = "ValWbsElem", required = true)
    protected String valWbsElem;
    @XmlElement(name = "GlAccount", required = true)
    protected String glAccount;
    @XmlElement(name = "IndProposeQuanx", required = true)
    protected String indProposeQuanx;
    @XmlElement(name = "Xstob", required = true)
    protected String xstob;
    @XmlElement(name = "EanUpc", required = true)
    protected String eanUpc;
    @XmlElement(name = "DelivNumbToSearch", required = true)
    protected String delivNumbToSearch;
    @XmlElement(name = "DelivItemToSearch", required = true)
    protected String delivItemToSearch;
    @XmlElement(name = "SerialnoAutoNumberassignment", required = true)
    protected String serialnoAutoNumberassignment;
    @XmlElement(name = "Vendrbatch", required = true)
    protected String vendrbatch;
    @XmlElement(name = "StgeType", required = true)
    protected String stgeType;
    @XmlElement(name = "StgeBin", required = true)
    protected String stgeBin;
    @XmlElement(name = "SuPlStck1", required = true)
    protected BigDecimal suPlStck1;
    @XmlElement(name = "StUnQtyy1", required = true)
    protected BigDecimal stUnQtyy1;
    @XmlElement(name = "StUnQtyy1Iso", required = true)
    protected String stUnQtyy1Iso;
    @XmlElement(name = "Unittype1", required = true)
    protected String unittype1;
    @XmlElement(name = "SuPlStck2", required = true)
    protected BigDecimal suPlStck2;
    @XmlElement(name = "StUnQtyy2", required = true)
    protected BigDecimal stUnQtyy2;
    @XmlElement(name = "StUnQtyy2Iso", required = true)
    protected String stUnQtyy2Iso;
    @XmlElement(name = "Unittype2", required = true)
    protected String unittype2;
    @XmlElement(name = "StgeTypePc", required = true)
    protected String stgeTypePc;
    @XmlElement(name = "StgeBinPc", required = true)
    protected String stgeBinPc;
    @XmlElement(name = "NoPstChgnt", required = true)
    protected String noPstChgnt;
    @XmlElement(name = "GrNumber", required = true)
    protected String grNumber;
    @XmlElement(name = "StgeTypeSt", required = true)
    protected String stgeTypeSt;
    @XmlElement(name = "StgeBinSt", required = true)
    protected String stgeBinSt;
    @XmlElement(name = "MatdocTrCancel", required = true)
    protected String matdocTrCancel;
    @XmlElement(name = "MatitemTrCancel", required = true)
    protected String matitemTrCancel;
    @XmlElement(name = "MatyearTrCancel", required = true)
    protected String matyearTrCancel;
    @XmlElement(name = "NoTransferReq", required = true)
    protected String noTransferReq;
    @XmlElement(name = "CoBusproc", required = true)
    protected String coBusproc;
    @XmlElement(name = "Acttype", required = true)
    protected String acttype;
    @XmlElement(name = "SupplVend", required = true)
    protected String supplVend;
    @XmlElement(name = "MaterialExternal", required = true)
    protected String materialExternal;
    @XmlElement(name = "MaterialGuid", required = true)
    protected String materialGuid;
    @XmlElement(name = "MaterialVersion", required = true)
    protected String materialVersion;
    @XmlElement(name = "MoveMatExternal", required = true)
    protected String moveMatExternal;
    @XmlElement(name = "MoveMatGuid", required = true)
    protected String moveMatGuid;
    @XmlElement(name = "MoveMatVersion", required = true)
    protected String moveMatVersion;
    @XmlElement(name = "FuncArea", required = true)
    protected String funcArea;
    @XmlElement(name = "TrPartBa", required = true)
    protected String trPartBa;
    @XmlElement(name = "ParCompco", required = true)
    protected String parCompco;
    @XmlElement(name = "DelivNumb", required = true)
    protected String delivNumb;
    @XmlElement(name = "DelivItem", required = true)
    protected String delivItem;
    @XmlElement(name = "NbSlips", required = true)
    protected String nbSlips;
    @XmlElement(name = "NbSlipsx", required = true)
    protected String nbSlipsx;
    @XmlElement(name = "GrRcptx", required = true)
    protected String grRcptx;
    @XmlElement(name = "UnloadPtx", required = true)
    protected String unloadPtx;
    @XmlElement(name = "SpecMvmt", required = true)
    protected String specMvmt;
    @XmlElement(name = "GrantNbr", required = true)
    protected String grantNbr;
    @XmlElement(name = "CmmtItemLong", required = true)
    protected String cmmtItemLong;
    @XmlElement(name = "FuncAreaLong", required = true)
    protected String funcAreaLong;
    @XmlElement(name = "LineId", required = true)
    protected String lineId;
    @XmlElement(name = "ParentId", required = true)
    protected String parentId;
    @XmlElement(name = "LineDepth", required = true)
    protected String lineDepth;
    @XmlElement(name = "Quantity", required = true)
    protected BigDecimal quantity;
    @XmlElement(name = "BaseUom", required = true)
    protected String baseUom;
    @XmlElement(name = "Longnum", required = true)
    protected String longnum;
    @XmlElement(name = "BudgetPeriod", required = true)
    protected String budgetPeriod;

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the plant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlant() {
        return plant;
    }

    /**
     * Sets the value of the plant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlant(String value) {
        this.plant = value;
    }

    /**
     * Gets the value of the stgeLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStgeLoc() {
        return stgeLoc;
    }

    /**
     * Sets the value of the stgeLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStgeLoc(String value) {
        this.stgeLoc = value;
    }

    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatch() {
        return batch;
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatch(String value) {
        this.batch = value;
    }

    /**
     * Gets the value of the moveType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveType() {
        return moveType;
    }

    /**
     * Sets the value of the moveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveType(String value) {
        this.moveType = value;
    }

    /**
     * Gets the value of the stckType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStckType() {
        return stckType;
    }

    /**
     * Sets the value of the stckType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStckType(String value) {
        this.stckType = value;
    }

    /**
     * Gets the value of the specStock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecStock() {
        return specStock;
    }

    /**
     * Sets the value of the specStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecStock(String value) {
        this.specStock = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomer(String value) {
        this.customer = value;
    }

    /**
     * Gets the value of the salesOrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesOrd() {
        return salesOrd;
    }

    /**
     * Sets the value of the salesOrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesOrd(String value) {
        this.salesOrd = value;
    }

    /**
     * Gets the value of the sOrdItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOrdItem() {
        return sOrdItem;
    }

    /**
     * Sets the value of the sOrdItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOrdItem(String value) {
        this.sOrdItem = value;
    }

    /**
     * Gets the value of the schedLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedLine() {
        return schedLine;
    }

    /**
     * Sets the value of the schedLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedLine(String value) {
        this.schedLine = value;
    }

    /**
     * Gets the value of the valType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValType() {
        return valType;
    }

    /**
     * Sets the value of the valType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValType(String value) {
        this.valType = value;
    }

    /**
     * Gets the value of the entryQnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEntryQnt() {
        return entryQnt;
    }

    /**
     * Sets the value of the entryQnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEntryQnt(BigDecimal value) {
        this.entryQnt = value;
    }

    /**
     * Gets the value of the entryUom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryUom() {
        return entryUom;
    }

    /**
     * Sets the value of the entryUom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryUom(String value) {
        this.entryUom = value;
    }

    /**
     * Gets the value of the entryUomIso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryUomIso() {
        return entryUomIso;
    }

    /**
     * Sets the value of the entryUomIso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryUomIso(String value) {
        this.entryUomIso = value;
    }

    /**
     * Gets the value of the poPrQnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPoPrQnt() {
        return poPrQnt;
    }

    /**
     * Sets the value of the poPrQnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPoPrQnt(BigDecimal value) {
        this.poPrQnt = value;
    }

    /**
     * Gets the value of the orderprUn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderprUn() {
        return orderprUn;
    }

    /**
     * Sets the value of the orderprUn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderprUn(String value) {
        this.orderprUn = value;
    }

    /**
     * Gets the value of the orderprUnIso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderprUnIso() {
        return orderprUnIso;
    }

    /**
     * Sets the value of the orderprUnIso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderprUnIso(String value) {
        this.orderprUnIso = value;
    }

    /**
     * Gets the value of the poNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoNumber() {
        return poNumber;
    }

    /**
     * Sets the value of the poNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoNumber(String value) {
        this.poNumber = value;
    }

    /**
     * Gets the value of the poItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoItem() {
        return poItem;
    }

    /**
     * Sets the value of the poItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoItem(String value) {
        this.poItem = value;
    }

    /**
     * Gets the value of the shipping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipping() {
        return shipping;
    }

    /**
     * Sets the value of the shipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipping(String value) {
        this.shipping = value;
    }

    /**
     * Gets the value of the compShip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompShip() {
        return compShip;
    }

    /**
     * Sets the value of the compShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompShip(String value) {
        this.compShip = value;
    }

    /**
     * Gets the value of the noMoreGr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoMoreGr() {
        return noMoreGr;
    }

    /**
     * Sets the value of the noMoreGr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoMoreGr(String value) {
        this.noMoreGr = value;
    }

    /**
     * Gets the value of the itemText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemText() {
        return itemText;
    }

    /**
     * Sets the value of the itemText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemText(String value) {
        this.itemText = value;
    }

    /**
     * Gets the value of the grRcpt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrRcpt() {
        return grRcpt;
    }

    /**
     * Sets the value of the grRcpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrRcpt(String value) {
        this.grRcpt = value;
    }

    /**
     * Gets the value of the unloadPt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnloadPt() {
        return unloadPt;
    }

    /**
     * Sets the value of the unloadPt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnloadPt(String value) {
        this.unloadPt = value;
    }

    /**
     * Gets the value of the costcenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostcenter() {
        return costcenter;
    }

    /**
     * Sets the value of the costcenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostcenter(String value) {
        this.costcenter = value;
    }

    /**
     * Gets the value of the orderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * Sets the value of the orderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderid(String value) {
        this.orderid = value;
    }

    /**
     * Gets the value of the orderItno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderItno() {
        return orderItno;
    }

    /**
     * Sets the value of the orderItno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderItno(String value) {
        this.orderItno = value;
    }

    /**
     * Gets the value of the calcMotive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalcMotive() {
        return calcMotive;
    }

    /**
     * Sets the value of the calcMotive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalcMotive(String value) {
        this.calcMotive = value;
    }

    /**
     * Gets the value of the assetNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetNo() {
        return assetNo;
    }

    /**
     * Sets the value of the assetNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetNo(String value) {
        this.assetNo = value;
    }

    /**
     * Gets the value of the subNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubNumber() {
        return subNumber;
    }

    /**
     * Sets the value of the subNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubNumber(String value) {
        this.subNumber = value;
    }

    /**
     * Gets the value of the reservNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservNo() {
        return reservNo;
    }

    /**
     * Sets the value of the reservNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservNo(String value) {
        this.reservNo = value;
    }

    /**
     * Gets the value of the resItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResItem() {
        return resItem;
    }

    /**
     * Sets the value of the resItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResItem(String value) {
        this.resItem = value;
    }

    /**
     * Gets the value of the resType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResType() {
        return resType;
    }

    /**
     * Sets the value of the resType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResType(String value) {
        this.resType = value;
    }

    /**
     * Gets the value of the withdrawn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithdrawn() {
        return withdrawn;
    }

    /**
     * Sets the value of the withdrawn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithdrawn(String value) {
        this.withdrawn = value;
    }

    /**
     * Gets the value of the moveMat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveMat() {
        return moveMat;
    }

    /**
     * Sets the value of the moveMat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveMat(String value) {
        this.moveMat = value;
    }

    /**
     * Gets the value of the movePlant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovePlant() {
        return movePlant;
    }

    /**
     * Sets the value of the movePlant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovePlant(String value) {
        this.movePlant = value;
    }

    /**
     * Gets the value of the moveStloc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveStloc() {
        return moveStloc;
    }

    /**
     * Sets the value of the moveStloc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveStloc(String value) {
        this.moveStloc = value;
    }

    /**
     * Gets the value of the moveBatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveBatch() {
        return moveBatch;
    }

    /**
     * Sets the value of the moveBatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveBatch(String value) {
        this.moveBatch = value;
    }

    /**
     * Gets the value of the moveValType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveValType() {
        return moveValType;
    }

    /**
     * Sets the value of the moveValType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveValType(String value) {
        this.moveValType = value;
    }

    /**
     * Gets the value of the mvtInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMvtInd() {
        return mvtInd;
    }

    /**
     * Sets the value of the mvtInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMvtInd(String value) {
        this.mvtInd = value;
    }

    /**
     * Gets the value of the moveReas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveReas() {
        return moveReas;
    }

    /**
     * Sets the value of the moveReas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveReas(String value) {
        this.moveReas = value;
    }

    /**
     * Gets the value of the rlEstKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRlEstKey() {
        return rlEstKey;
    }

    /**
     * Sets the value of the rlEstKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRlEstKey(String value) {
        this.rlEstKey = value;
    }

    /**
     * Gets the value of the refDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDate() {
        return refDate;
    }

    /**
     * Sets the value of the refDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDate(String value) {
        this.refDate = value;
    }

    /**
     * Gets the value of the costObj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObj() {
        return costObj;
    }

    /**
     * Sets the value of the costObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObj(String value) {
        this.costObj = value;
    }

    /**
     * Gets the value of the profitSegmNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfitSegmNo() {
        return profitSegmNo;
    }

    /**
     * Sets the value of the profitSegmNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfitSegmNo(String value) {
        this.profitSegmNo = value;
    }

    /**
     * Gets the value of the profitCtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfitCtr() {
        return profitCtr;
    }

    /**
     * Sets the value of the profitCtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfitCtr(String value) {
        this.profitCtr = value;
    }

    /**
     * Gets the value of the wbsElem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWbsElem() {
        return wbsElem;
    }

    /**
     * Sets the value of the wbsElem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWbsElem(String value) {
        this.wbsElem = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetwork(String value) {
        this.network = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivity(String value) {
        this.activity = value;
    }

    /**
     * Gets the value of the partAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartAcct() {
        return partAcct;
    }

    /**
     * Sets the value of the partAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartAcct(String value) {
        this.partAcct = value;
    }

    /**
     * Gets the value of the amountLc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountLc() {
        return amountLc;
    }

    /**
     * Sets the value of the amountLc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountLc(BigDecimal value) {
        this.amountLc = value;
    }

    /**
     * Gets the value of the amountSv property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountSv() {
        return amountSv;
    }

    /**
     * Sets the value of the amountSv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountSv(BigDecimal value) {
        this.amountSv = value;
    }

    /**
     * Gets the value of the refDocYr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDocYr() {
        return refDocYr;
    }

    /**
     * Sets the value of the refDocYr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDocYr(String value) {
        this.refDocYr = value;
    }

    /**
     * Gets the value of the refDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDoc() {
        return refDoc;
    }

    /**
     * Sets the value of the refDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDoc(String value) {
        this.refDoc = value;
    }

    /**
     * Gets the value of the refDocIt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDocIt() {
        return refDocIt;
    }

    /**
     * Sets the value of the refDocIt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDocIt(String value) {
        this.refDocIt = value;
    }

    /**
     * Gets the value of the expirydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirydate() {
        return expirydate;
    }

    /**
     * Sets the value of the expirydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirydate(String value) {
        this.expirydate = value;
    }

    /**
     * Gets the value of the prodDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdDate() {
        return prodDate;
    }

    /**
     * Sets the value of the prodDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdDate(String value) {
        this.prodDate = value;
    }

    /**
     * Gets the value of the fund property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFund() {
        return fund;
    }

    /**
     * Sets the value of the fund property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFund(String value) {
        this.fund = value;
    }

    /**
     * Gets the value of the fundsCtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundsCtr() {
        return fundsCtr;
    }

    /**
     * Sets the value of the fundsCtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundsCtr(String value) {
        this.fundsCtr = value;
    }

    /**
     * Gets the value of the cmmtItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmmtItem() {
        return cmmtItem;
    }

    /**
     * Sets the value of the cmmtItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmmtItem(String value) {
        this.cmmtItem = value;
    }

    /**
     * Gets the value of the valSalesOrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValSalesOrd() {
        return valSalesOrd;
    }

    /**
     * Sets the value of the valSalesOrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValSalesOrd(String value) {
        this.valSalesOrd = value;
    }

    /**
     * Gets the value of the valSOrdItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValSOrdItem() {
        return valSOrdItem;
    }

    /**
     * Sets the value of the valSOrdItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValSOrdItem(String value) {
        this.valSOrdItem = value;
    }

    /**
     * Gets the value of the valWbsElem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValWbsElem() {
        return valWbsElem;
    }

    /**
     * Sets the value of the valWbsElem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValWbsElem(String value) {
        this.valWbsElem = value;
    }

    /**
     * Gets the value of the glAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlAccount() {
        return glAccount;
    }

    /**
     * Sets the value of the glAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlAccount(String value) {
        this.glAccount = value;
    }

    /**
     * Gets the value of the indProposeQuanx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndProposeQuanx() {
        return indProposeQuanx;
    }

    /**
     * Sets the value of the indProposeQuanx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndProposeQuanx(String value) {
        this.indProposeQuanx = value;
    }

    /**
     * Gets the value of the xstob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXstob() {
        return xstob;
    }

    /**
     * Sets the value of the xstob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXstob(String value) {
        this.xstob = value;
    }

    /**
     * Gets the value of the eanUpc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEanUpc() {
        return eanUpc;
    }

    /**
     * Sets the value of the eanUpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEanUpc(String value) {
        this.eanUpc = value;
    }

    /**
     * Gets the value of the delivNumbToSearch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelivNumbToSearch() {
        return delivNumbToSearch;
    }

    /**
     * Sets the value of the delivNumbToSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelivNumbToSearch(String value) {
        this.delivNumbToSearch = value;
    }

    /**
     * Gets the value of the delivItemToSearch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelivItemToSearch() {
        return delivItemToSearch;
    }

    /**
     * Sets the value of the delivItemToSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelivItemToSearch(String value) {
        this.delivItemToSearch = value;
    }

    /**
     * Gets the value of the serialnoAutoNumberassignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialnoAutoNumberassignment() {
        return serialnoAutoNumberassignment;
    }

    /**
     * Sets the value of the serialnoAutoNumberassignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialnoAutoNumberassignment(String value) {
        this.serialnoAutoNumberassignment = value;
    }

    /**
     * Gets the value of the vendrbatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendrbatch() {
        return vendrbatch;
    }

    /**
     * Sets the value of the vendrbatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendrbatch(String value) {
        this.vendrbatch = value;
    }

    /**
     * Gets the value of the stgeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStgeType() {
        return stgeType;
    }

    /**
     * Sets the value of the stgeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStgeType(String value) {
        this.stgeType = value;
    }

    /**
     * Gets the value of the stgeBin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStgeBin() {
        return stgeBin;
    }

    /**
     * Sets the value of the stgeBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStgeBin(String value) {
        this.stgeBin = value;
    }

    /**
     * Gets the value of the suPlStck1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSuPlStck1() {
        return suPlStck1;
    }

    /**
     * Sets the value of the suPlStck1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSuPlStck1(BigDecimal value) {
        this.suPlStck1 = value;
    }

    /**
     * Gets the value of the stUnQtyy1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStUnQtyy1() {
        return stUnQtyy1;
    }

    /**
     * Sets the value of the stUnQtyy1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStUnQtyy1(BigDecimal value) {
        this.stUnQtyy1 = value;
    }

    /**
     * Gets the value of the stUnQtyy1Iso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStUnQtyy1Iso() {
        return stUnQtyy1Iso;
    }

    /**
     * Sets the value of the stUnQtyy1Iso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStUnQtyy1Iso(String value) {
        this.stUnQtyy1Iso = value;
    }

    /**
     * Gets the value of the unittype1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnittype1() {
        return unittype1;
    }

    /**
     * Sets the value of the unittype1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnittype1(String value) {
        this.unittype1 = value;
    }

    /**
     * Gets the value of the suPlStck2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSuPlStck2() {
        return suPlStck2;
    }

    /**
     * Sets the value of the suPlStck2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSuPlStck2(BigDecimal value) {
        this.suPlStck2 = value;
    }

    /**
     * Gets the value of the stUnQtyy2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStUnQtyy2() {
        return stUnQtyy2;
    }

    /**
     * Sets the value of the stUnQtyy2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStUnQtyy2(BigDecimal value) {
        this.stUnQtyy2 = value;
    }

    /**
     * Gets the value of the stUnQtyy2Iso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStUnQtyy2Iso() {
        return stUnQtyy2Iso;
    }

    /**
     * Sets the value of the stUnQtyy2Iso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStUnQtyy2Iso(String value) {
        this.stUnQtyy2Iso = value;
    }

    /**
     * Gets the value of the unittype2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnittype2() {
        return unittype2;
    }

    /**
     * Sets the value of the unittype2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnittype2(String value) {
        this.unittype2 = value;
    }

    /**
     * Gets the value of the stgeTypePc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStgeTypePc() {
        return stgeTypePc;
    }

    /**
     * Sets the value of the stgeTypePc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStgeTypePc(String value) {
        this.stgeTypePc = value;
    }

    /**
     * Gets the value of the stgeBinPc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStgeBinPc() {
        return stgeBinPc;
    }

    /**
     * Sets the value of the stgeBinPc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStgeBinPc(String value) {
        this.stgeBinPc = value;
    }

    /**
     * Gets the value of the noPstChgnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoPstChgnt() {
        return noPstChgnt;
    }

    /**
     * Sets the value of the noPstChgnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoPstChgnt(String value) {
        this.noPstChgnt = value;
    }

    /**
     * Gets the value of the grNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrNumber() {
        return grNumber;
    }

    /**
     * Sets the value of the grNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrNumber(String value) {
        this.grNumber = value;
    }

    /**
     * Gets the value of the stgeTypeSt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStgeTypeSt() {
        return stgeTypeSt;
    }

    /**
     * Sets the value of the stgeTypeSt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStgeTypeSt(String value) {
        this.stgeTypeSt = value;
    }

    /**
     * Gets the value of the stgeBinSt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStgeBinSt() {
        return stgeBinSt;
    }

    /**
     * Sets the value of the stgeBinSt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStgeBinSt(String value) {
        this.stgeBinSt = value;
    }

    /**
     * Gets the value of the matdocTrCancel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatdocTrCancel() {
        return matdocTrCancel;
    }

    /**
     * Sets the value of the matdocTrCancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatdocTrCancel(String value) {
        this.matdocTrCancel = value;
    }

    /**
     * Gets the value of the matitemTrCancel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatitemTrCancel() {
        return matitemTrCancel;
    }

    /**
     * Sets the value of the matitemTrCancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatitemTrCancel(String value) {
        this.matitemTrCancel = value;
    }

    /**
     * Gets the value of the matyearTrCancel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatyearTrCancel() {
        return matyearTrCancel;
    }

    /**
     * Sets the value of the matyearTrCancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatyearTrCancel(String value) {
        this.matyearTrCancel = value;
    }

    /**
     * Gets the value of the noTransferReq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoTransferReq() {
        return noTransferReq;
    }

    /**
     * Sets the value of the noTransferReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoTransferReq(String value) {
        this.noTransferReq = value;
    }

    /**
     * Gets the value of the coBusproc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoBusproc() {
        return coBusproc;
    }

    /**
     * Sets the value of the coBusproc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoBusproc(String value) {
        this.coBusproc = value;
    }

    /**
     * Gets the value of the acttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActtype() {
        return acttype;
    }

    /**
     * Sets the value of the acttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActtype(String value) {
        this.acttype = value;
    }

    /**
     * Gets the value of the supplVend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplVend() {
        return supplVend;
    }

    /**
     * Sets the value of the supplVend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplVend(String value) {
        this.supplVend = value;
    }

    /**
     * Gets the value of the materialExternal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialExternal() {
        return materialExternal;
    }

    /**
     * Sets the value of the materialExternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialExternal(String value) {
        this.materialExternal = value;
    }

    /**
     * Gets the value of the materialGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialGuid() {
        return materialGuid;
    }

    /**
     * Sets the value of the materialGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialGuid(String value) {
        this.materialGuid = value;
    }

    /**
     * Gets the value of the materialVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialVersion() {
        return materialVersion;
    }

    /**
     * Sets the value of the materialVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialVersion(String value) {
        this.materialVersion = value;
    }

    /**
     * Gets the value of the moveMatExternal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveMatExternal() {
        return moveMatExternal;
    }

    /**
     * Sets the value of the moveMatExternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveMatExternal(String value) {
        this.moveMatExternal = value;
    }

    /**
     * Gets the value of the moveMatGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveMatGuid() {
        return moveMatGuid;
    }

    /**
     * Sets the value of the moveMatGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveMatGuid(String value) {
        this.moveMatGuid = value;
    }

    /**
     * Gets the value of the moveMatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveMatVersion() {
        return moveMatVersion;
    }

    /**
     * Sets the value of the moveMatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveMatVersion(String value) {
        this.moveMatVersion = value;
    }

    /**
     * Gets the value of the funcArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuncArea() {
        return funcArea;
    }

    /**
     * Sets the value of the funcArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuncArea(String value) {
        this.funcArea = value;
    }

    /**
     * Gets the value of the trPartBa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrPartBa() {
        return trPartBa;
    }

    /**
     * Sets the value of the trPartBa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrPartBa(String value) {
        this.trPartBa = value;
    }

    /**
     * Gets the value of the parCompco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParCompco() {
        return parCompco;
    }

    /**
     * Sets the value of the parCompco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParCompco(String value) {
        this.parCompco = value;
    }

    /**
     * Gets the value of the delivNumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelivNumb() {
        return delivNumb;
    }

    /**
     * Sets the value of the delivNumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelivNumb(String value) {
        this.delivNumb = value;
    }

    /**
     * Gets the value of the delivItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelivItem() {
        return delivItem;
    }

    /**
     * Sets the value of the delivItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelivItem(String value) {
        this.delivItem = value;
    }

    /**
     * Gets the value of the nbSlips property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbSlips() {
        return nbSlips;
    }

    /**
     * Sets the value of the nbSlips property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbSlips(String value) {
        this.nbSlips = value;
    }

    /**
     * Gets the value of the nbSlipsx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbSlipsx() {
        return nbSlipsx;
    }

    /**
     * Sets the value of the nbSlipsx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbSlipsx(String value) {
        this.nbSlipsx = value;
    }

    /**
     * Gets the value of the grRcptx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrRcptx() {
        return grRcptx;
    }

    /**
     * Sets the value of the grRcptx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrRcptx(String value) {
        this.grRcptx = value;
    }

    /**
     * Gets the value of the unloadPtx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnloadPtx() {
        return unloadPtx;
    }

    /**
     * Sets the value of the unloadPtx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnloadPtx(String value) {
        this.unloadPtx = value;
    }

    /**
     * Gets the value of the specMvmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecMvmt() {
        return specMvmt;
    }

    /**
     * Sets the value of the specMvmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecMvmt(String value) {
        this.specMvmt = value;
    }

    /**
     * Gets the value of the grantNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrantNbr() {
        return grantNbr;
    }

    /**
     * Sets the value of the grantNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrantNbr(String value) {
        this.grantNbr = value;
    }

    /**
     * Gets the value of the cmmtItemLong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmmtItemLong() {
        return cmmtItemLong;
    }

    /**
     * Sets the value of the cmmtItemLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmmtItemLong(String value) {
        this.cmmtItemLong = value;
    }

    /**
     * Gets the value of the funcAreaLong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuncAreaLong() {
        return funcAreaLong;
    }

    /**
     * Sets the value of the funcAreaLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuncAreaLong(String value) {
        this.funcAreaLong = value;
    }

    /**
     * Gets the value of the lineId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * Sets the value of the lineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineId(String value) {
        this.lineId = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentId(String value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the lineDepth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineDepth() {
        return lineDepth;
    }

    /**
     * Sets the value of the lineDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineDepth(String value) {
        this.lineDepth = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantity(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the baseUom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseUom() {
        return baseUom;
    }

    /**
     * Sets the value of the baseUom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseUom(String value) {
        this.baseUom = value;
    }

    /**
     * Gets the value of the longnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongnum() {
        return longnum;
    }

    /**
     * Sets the value of the longnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongnum(String value) {
        this.longnum = value;
    }

    /**
     * Gets the value of the budgetPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBudgetPeriod() {
        return budgetPeriod;
    }

    /**
     * Sets the value of the budgetPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBudgetPeriod(String value) {
        this.budgetPeriod = value;
    }

}
