//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 04:19:12 PM WIB 
//


package id.co.qualitas.domain.webservice.goodsmvt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bapi2017GmHeadRet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bapi2017GmHeadRet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MatDoc" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="DocYear" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bapi2017GmHeadRet", propOrder = {
    "matDoc",
    "docYear"
})
public class Bapi2017GmHeadRet {

    @XmlElement(name = "MatDoc", required = true)
    protected String matDoc;
    @XmlElement(name = "DocYear", required = true)
    protected String docYear;

    /**
     * Gets the value of the matDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatDoc() {
        return matDoc;
    }

    /**
     * Sets the value of the matDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatDoc(String value) {
        this.matDoc = value;
    }

    /**
     * Gets the value of the docYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocYear() {
        return docYear;
    }

    /**
     * Sets the value of the docYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocYear(String value) {
        this.docYear = value;
    }

}
