//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 04:19:12 PM WIB 
//


package id.co.qualitas.domain.webservice.goodsmvt;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for _-cwm_-bapi2017GmItemCreate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_-cwm_-bapi2017GmItemCreate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MatdocItm" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="QuantityPme" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="BaseUomPme" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="EntryQntPme" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="EntryUomPme" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_-cwm_-bapi2017GmItemCreate", propOrder = {
    "matdocItm",
    "quantityPme",
    "baseUomPme",
    "entryQntPme",
    "entryUomPme"
})
public class CwmBapi2017GmItemCreate {

    @XmlElement(name = "MatdocItm", required = true)
    protected String matdocItm;
    @XmlElement(name = "QuantityPme", required = true)
    protected BigDecimal quantityPme;
    @XmlElement(name = "BaseUomPme", required = true)
    protected String baseUomPme;
    @XmlElement(name = "EntryQntPme", required = true)
    protected BigDecimal entryQntPme;
    @XmlElement(name = "EntryUomPme", required = true)
    protected String entryUomPme;

    /**
     * Gets the value of the matdocItm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatdocItm() {
        return matdocItm;
    }

    /**
     * Sets the value of the matdocItm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatdocItm(String value) {
        this.matdocItm = value;
    }

    /**
     * Gets the value of the quantityPme property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantityPme() {
        return quantityPme;
    }

    /**
     * Sets the value of the quantityPme property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantityPme(BigDecimal value) {
        this.quantityPme = value;
    }

    /**
     * Gets the value of the baseUomPme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseUomPme() {
        return baseUomPme;
    }

    /**
     * Sets the value of the baseUomPme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseUomPme(String value) {
        this.baseUomPme = value;
    }

    /**
     * Gets the value of the entryQntPme property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEntryQntPme() {
        return entryQntPme;
    }

    /**
     * Sets the value of the entryQntPme property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEntryQntPme(BigDecimal value) {
        this.entryQntPme = value;
    }

    /**
     * Gets the value of the entryUomPme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryUomPme() {
        return entryUomPme;
    }

    /**
     * Sets the value of the entryUomPme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryUomPme(String value) {
        this.entryUomPme = value;
    }

}
