//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 04:19:12 PM WIB 
//


package id.co.qualitas.domain.webservice.goodsmvt;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for _-spe_-bapi2017ServicepartData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_-spe_-bapi2017ServicepartData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LineId" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="RetAuthNumber" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="DelivNumber" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="DelivItem" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="HuNumber" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="InspoutGuid" type="{urn:sap-com:document:sap:rfc:functions}char32"/&gt;
 *         &lt;element name="Event" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="Date" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="Time" type="{urn:sap-com:document:sap:rfc:functions}time"/&gt;
 *         &lt;element name="Zonlo" type="{urn:sap-com:document:sap:rfc:functions}char6"/&gt;
 *         &lt;element name="Timestamp" type="{urn:sap-com:document:sap:rfc:functions}decimal15.0"/&gt;
 *         &lt;element name="ScrapIndicator" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="KeepQuantity" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="GtsStockType" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="MoveGtsStockType" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="KeepQuantityConversion" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ZeroQuantity" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="Numerator" type="{urn:sap-com:document:sap:rfc:functions}decimal5.0"/&gt;
 *         &lt;element name="Denominatr" type="{urn:sap-com:document:sap:rfc:functions}decimal5.0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_-spe_-bapi2017ServicepartData", propOrder = {
    "lineId",
    "retAuthNumber",
    "delivNumber",
    "delivItem",
    "huNumber",
    "inspoutGuid",
    "event",
    "date",
    "time",
    "zonlo",
    "timestamp",
    "scrapIndicator",
    "keepQuantity",
    "gtsStockType",
    "moveGtsStockType",
    "keepQuantityConversion",
    "zeroQuantity",
    "numerator",
    "denominatr"
})
public class SpeBapi2017ServicepartData {

    @XmlElement(name = "LineId", required = true)
    protected String lineId;
    @XmlElement(name = "RetAuthNumber", required = true)
    protected String retAuthNumber;
    @XmlElement(name = "DelivNumber", required = true)
    protected String delivNumber;
    @XmlElement(name = "DelivItem", required = true)
    protected String delivItem;
    @XmlElement(name = "HuNumber", required = true)
    protected String huNumber;
    @XmlElement(name = "InspoutGuid", required = true)
    protected String inspoutGuid;
    @XmlElement(name = "Event", required = true)
    protected String event;
    @XmlElement(name = "Date", required = true)
    protected String date;
    @XmlElement(name = "Time", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;
    @XmlElement(name = "Zonlo", required = true)
    protected String zonlo;
    @XmlElement(name = "Timestamp", required = true)
    protected BigDecimal timestamp;
    @XmlElement(name = "ScrapIndicator", required = true)
    protected String scrapIndicator;
    @XmlElement(name = "KeepQuantity", required = true)
    protected BigDecimal keepQuantity;
    @XmlElement(name = "GtsStockType", required = true)
    protected String gtsStockType;
    @XmlElement(name = "MoveGtsStockType", required = true)
    protected String moveGtsStockType;
    @XmlElement(name = "KeepQuantityConversion", required = true)
    protected String keepQuantityConversion;
    @XmlElement(name = "ZeroQuantity", required = true)
    protected String zeroQuantity;
    @XmlElement(name = "Numerator", required = true)
    protected BigDecimal numerator;
    @XmlElement(name = "Denominatr", required = true)
    protected BigDecimal denominatr;

    /**
     * Gets the value of the lineId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * Sets the value of the lineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineId(String value) {
        this.lineId = value;
    }

    /**
     * Gets the value of the retAuthNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetAuthNumber() {
        return retAuthNumber;
    }

    /**
     * Sets the value of the retAuthNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetAuthNumber(String value) {
        this.retAuthNumber = value;
    }

    /**
     * Gets the value of the delivNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelivNumber() {
        return delivNumber;
    }

    /**
     * Sets the value of the delivNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelivNumber(String value) {
        this.delivNumber = value;
    }

    /**
     * Gets the value of the delivItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelivItem() {
        return delivItem;
    }

    /**
     * Sets the value of the delivItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelivItem(String value) {
        this.delivItem = value;
    }

    /**
     * Gets the value of the huNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHuNumber() {
        return huNumber;
    }

    /**
     * Sets the value of the huNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHuNumber(String value) {
        this.huNumber = value;
    }

    /**
     * Gets the value of the inspoutGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspoutGuid() {
        return inspoutGuid;
    }

    /**
     * Sets the value of the inspoutGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspoutGuid(String value) {
        this.inspoutGuid = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvent(String value) {
        this.event = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the zonlo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZonlo() {
        return zonlo;
    }

    /**
     * Sets the value of the zonlo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZonlo(String value) {
        this.zonlo = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTimestamp(BigDecimal value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the scrapIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrapIndicator() {
        return scrapIndicator;
    }

    /**
     * Sets the value of the scrapIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrapIndicator(String value) {
        this.scrapIndicator = value;
    }

    /**
     * Gets the value of the keepQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKeepQuantity() {
        return keepQuantity;
    }

    /**
     * Sets the value of the keepQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKeepQuantity(BigDecimal value) {
        this.keepQuantity = value;
    }

    /**
     * Gets the value of the gtsStockType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGtsStockType() {
        return gtsStockType;
    }

    /**
     * Sets the value of the gtsStockType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGtsStockType(String value) {
        this.gtsStockType = value;
    }

    /**
     * Gets the value of the moveGtsStockType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveGtsStockType() {
        return moveGtsStockType;
    }

    /**
     * Sets the value of the moveGtsStockType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveGtsStockType(String value) {
        this.moveGtsStockType = value;
    }

    /**
     * Gets the value of the keepQuantityConversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeepQuantityConversion() {
        return keepQuantityConversion;
    }

    /**
     * Sets the value of the keepQuantityConversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeepQuantityConversion(String value) {
        this.keepQuantityConversion = value;
    }

    /**
     * Gets the value of the zeroQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZeroQuantity() {
        return zeroQuantity;
    }

    /**
     * Sets the value of the zeroQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZeroQuantity(String value) {
        this.zeroQuantity = value;
    }

    /**
     * Gets the value of the numerator property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumerator() {
        return numerator;
    }

    /**
     * Sets the value of the numerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumerator(BigDecimal value) {
        this.numerator = value;
    }

    /**
     * Gets the value of the denominatr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDenominatr() {
        return denominatr;
    }

    /**
     * Sets the value of the denominatr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDenominatr(BigDecimal value) {
        this.denominatr = value;
    }

}
