//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 04:19:12 PM WIB 
//


package id.co.qualitas.domain.webservice.goodsmvt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Extensionin" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfBapiparex" minOccurs="0"/&gt;
 *         &lt;element name="GoodsmvtCode" type="{urn:sap-com:document:sap:soap:functions:mc-style}Bapi2017GmCode" minOccurs="0"/&gt;
 *         &lt;element name="GoodsmvtHeader" type="{urn:sap-com:document:sap:soap:functions:mc-style}Bapi2017GmHead01"/&gt;
 *         &lt;element name="GoodsmvtItem" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfBapi2017GmItemCreate"/&gt;
 *         &lt;element name="GoodsmvtItemCwm" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOf_-cwm_-bapi2017GmItemCreate" minOccurs="0"/&gt;
 *         &lt;element name="GoodsmvtRefEwm" type="{urn:sap-com:document:sap:soap:functions:mc-style}_-spe_-bapi2017GmRefEwm" minOccurs="0"/&gt;
 *         &lt;element name="GoodsmvtSerialnumber" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfBapi2017GmSerialnumber" minOccurs="0"/&gt;
 *         &lt;element name="GoodsmvtServPartData" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOf_-spe_-bapi2017ServicepartData" minOccurs="0"/&gt;
 *         &lt;element name="Return" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfBapiret2"/&gt;
 *         &lt;element name="Testrun" type="{urn:sap-com:document:sap:rfc:functions}char1" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extensionin",
    "goodsmvtCode",
    "goodsmvtHeader",
    "goodsmvtItem",
    "goodsmvtItemCwm",
    "goodsmvtRefEwm",
    "goodsmvtSerialnumber",
    "goodsmvtServPartData",
    "_return",
    "testrun"
})
@XmlRootElement(name = "ZfmWbGoodsmvt")
public class ZfmWbGoodsmvt {

    @XmlElement(name = "Extensionin")
    protected TableOfBapiparex extensionin;
    @XmlElement(name = "GoodsmvtCode")
    protected Bapi2017GmCode goodsmvtCode;
    @XmlElement(name = "GoodsmvtHeader", required = true)
    protected Bapi2017GmHead01 goodsmvtHeader;
    @XmlElement(name = "GoodsmvtItem", required = true)
    protected TableOfBapi2017GmItemCreate goodsmvtItem;
    @XmlElement(name = "GoodsmvtItemCwm")
    protected TableOfCwmBapi2017GmItemCreate goodsmvtItemCwm;
    @XmlElement(name = "GoodsmvtRefEwm")
    protected SpeBapi2017GmRefEwm goodsmvtRefEwm;
    @XmlElement(name = "GoodsmvtSerialnumber")
    protected TableOfBapi2017GmSerialnumber goodsmvtSerialnumber;
    @XmlElement(name = "GoodsmvtServPartData")
    protected TableOfSpeBapi2017ServicepartData goodsmvtServPartData;
    @XmlElement(name = "Return", required = true)
    protected TableOfBapiret2 _return;
    @XmlElement(name = "Testrun")
    protected String testrun;

    /**
     * Gets the value of the extensionin property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfBapiparex }
     *     
     */
    public TableOfBapiparex getExtensionin() {
        return extensionin;
    }

    /**
     * Sets the value of the extensionin property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfBapiparex }
     *     
     */
    public void setExtensionin(TableOfBapiparex value) {
        this.extensionin = value;
    }

    /**
     * Gets the value of the goodsmvtCode property.
     * 
     * @return
     *     possible object is
     *     {@link Bapi2017GmCode }
     *     
     */
    public Bapi2017GmCode getGoodsmvtCode() {
        return goodsmvtCode;
    }

    /**
     * Sets the value of the goodsmvtCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bapi2017GmCode }
     *     
     */
    public void setGoodsmvtCode(Bapi2017GmCode value) {
        this.goodsmvtCode = value;
    }

    /**
     * Gets the value of the goodsmvtHeader property.
     * 
     * @return
     *     possible object is
     *     {@link Bapi2017GmHead01 }
     *     
     */
    public Bapi2017GmHead01 getGoodsmvtHeader() {
        return goodsmvtHeader;
    }

    /**
     * Sets the value of the goodsmvtHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bapi2017GmHead01 }
     *     
     */
    public void setGoodsmvtHeader(Bapi2017GmHead01 value) {
        this.goodsmvtHeader = value;
    }

    /**
     * Gets the value of the goodsmvtItem property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfBapi2017GmItemCreate }
     *     
     */
    public TableOfBapi2017GmItemCreate getGoodsmvtItem() {
        return goodsmvtItem;
    }

    /**
     * Sets the value of the goodsmvtItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfBapi2017GmItemCreate }
     *     
     */
    public void setGoodsmvtItem(TableOfBapi2017GmItemCreate value) {
        this.goodsmvtItem = value;
    }

    /**
     * Gets the value of the goodsmvtItemCwm property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfCwmBapi2017GmItemCreate }
     *     
     */
    public TableOfCwmBapi2017GmItemCreate getGoodsmvtItemCwm() {
        return goodsmvtItemCwm;
    }

    /**
     * Sets the value of the goodsmvtItemCwm property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfCwmBapi2017GmItemCreate }
     *     
     */
    public void setGoodsmvtItemCwm(TableOfCwmBapi2017GmItemCreate value) {
        this.goodsmvtItemCwm = value;
    }

    /**
     * Gets the value of the goodsmvtRefEwm property.
     * 
     * @return
     *     possible object is
     *     {@link SpeBapi2017GmRefEwm }
     *     
     */
    public SpeBapi2017GmRefEwm getGoodsmvtRefEwm() {
        return goodsmvtRefEwm;
    }

    /**
     * Sets the value of the goodsmvtRefEwm property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeBapi2017GmRefEwm }
     *     
     */
    public void setGoodsmvtRefEwm(SpeBapi2017GmRefEwm value) {
        this.goodsmvtRefEwm = value;
    }

    /**
     * Gets the value of the goodsmvtSerialnumber property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfBapi2017GmSerialnumber }
     *     
     */
    public TableOfBapi2017GmSerialnumber getGoodsmvtSerialnumber() {
        return goodsmvtSerialnumber;
    }

    /**
     * Sets the value of the goodsmvtSerialnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfBapi2017GmSerialnumber }
     *     
     */
    public void setGoodsmvtSerialnumber(TableOfBapi2017GmSerialnumber value) {
        this.goodsmvtSerialnumber = value;
    }

    /**
     * Gets the value of the goodsmvtServPartData property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfSpeBapi2017ServicepartData }
     *     
     */
    public TableOfSpeBapi2017ServicepartData getGoodsmvtServPartData() {
        return goodsmvtServPartData;
    }

    /**
     * Sets the value of the goodsmvtServPartData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfSpeBapi2017ServicepartData }
     *     
     */
    public void setGoodsmvtServPartData(TableOfSpeBapi2017ServicepartData value) {
        this.goodsmvtServPartData = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfBapiret2 }
     *     
     */
    public TableOfBapiret2 getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfBapiret2 }
     *     
     */
    public void setReturn(TableOfBapiret2 value) {
        this._return = value;
    }

    /**
     * Gets the value of the testrun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestrun() {
        return testrun;
    }

    /**
     * Sets the value of the testrun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestrun(String value) {
        this.testrun = value;
    }

}
