//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 04:19:12 PM WIB 
//


package id.co.qualitas.domain.webservice.goodsmvt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Extensionin" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfBapiparex" minOccurs="0"/&gt;
 *         &lt;element name="GoodsmvtHeadret" type="{urn:sap-com:document:sap:soap:functions:mc-style}Bapi2017GmHeadRet"/&gt;
 *         &lt;element name="GoodsmvtItem" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfBapi2017GmItemCreate"/&gt;
 *         &lt;element name="GoodsmvtItemCwm" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOf_-cwm_-bapi2017GmItemCreate" minOccurs="0"/&gt;
 *         &lt;element name="GoodsmvtSerialnumber" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfBapi2017GmSerialnumber" minOccurs="0"/&gt;
 *         &lt;element name="GoodsmvtServPartData" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOf_-spe_-bapi2017ServicepartData" minOccurs="0"/&gt;
 *         &lt;element name="Matdocumentyear" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="Materialdocument" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="Return" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfBapiret2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extensionin",
    "goodsmvtHeadret",
    "goodsmvtItem",
    "goodsmvtItemCwm",
    "goodsmvtSerialnumber",
    "goodsmvtServPartData",
    "matdocumentyear",
    "materialdocument",
    "_return"
})
@XmlRootElement(name = "ZfmWbGoodsmvtResponse")
public class ZfmWbGoodsmvtResponse {

    @XmlElement(name = "Extensionin")
    protected TableOfBapiparex extensionin;
    @XmlElement(name = "GoodsmvtHeadret", required = true)
    protected Bapi2017GmHeadRet goodsmvtHeadret;
    @XmlElement(name = "GoodsmvtItem", required = true)
    protected TableOfBapi2017GmItemCreate goodsmvtItem;
    @XmlElement(name = "GoodsmvtItemCwm")
    protected TableOfCwmBapi2017GmItemCreate goodsmvtItemCwm;
    @XmlElement(name = "GoodsmvtSerialnumber")
    protected TableOfBapi2017GmSerialnumber goodsmvtSerialnumber;
    @XmlElement(name = "GoodsmvtServPartData")
    protected TableOfSpeBapi2017ServicepartData goodsmvtServPartData;
    @XmlElement(name = "Matdocumentyear", required = true)
    protected String matdocumentyear;
    @XmlElement(name = "Materialdocument", required = true)
    protected String materialdocument;
    @XmlElement(name = "Return", required = true)
    protected TableOfBapiret2 _return;

    /**
     * Gets the value of the extensionin property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfBapiparex }
     *     
     */
    public TableOfBapiparex getExtensionin() {
        return extensionin;
    }

    /**
     * Sets the value of the extensionin property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfBapiparex }
     *     
     */
    public void setExtensionin(TableOfBapiparex value) {
        this.extensionin = value;
    }

    /**
     * Gets the value of the goodsmvtHeadret property.
     * 
     * @return
     *     possible object is
     *     {@link Bapi2017GmHeadRet }
     *     
     */
    public Bapi2017GmHeadRet getGoodsmvtHeadret() {
        return goodsmvtHeadret;
    }

    /**
     * Sets the value of the goodsmvtHeadret property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bapi2017GmHeadRet }
     *     
     */
    public void setGoodsmvtHeadret(Bapi2017GmHeadRet value) {
        this.goodsmvtHeadret = value;
    }

    /**
     * Gets the value of the goodsmvtItem property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfBapi2017GmItemCreate }
     *     
     */
    public TableOfBapi2017GmItemCreate getGoodsmvtItem() {
        return goodsmvtItem;
    }

    /**
     * Sets the value of the goodsmvtItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfBapi2017GmItemCreate }
     *     
     */
    public void setGoodsmvtItem(TableOfBapi2017GmItemCreate value) {
        this.goodsmvtItem = value;
    }

    /**
     * Gets the value of the goodsmvtItemCwm property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfCwmBapi2017GmItemCreate }
     *     
     */
    public TableOfCwmBapi2017GmItemCreate getGoodsmvtItemCwm() {
        return goodsmvtItemCwm;
    }

    /**
     * Sets the value of the goodsmvtItemCwm property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfCwmBapi2017GmItemCreate }
     *     
     */
    public void setGoodsmvtItemCwm(TableOfCwmBapi2017GmItemCreate value) {
        this.goodsmvtItemCwm = value;
    }

    /**
     * Gets the value of the goodsmvtSerialnumber property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfBapi2017GmSerialnumber }
     *     
     */
    public TableOfBapi2017GmSerialnumber getGoodsmvtSerialnumber() {
        return goodsmvtSerialnumber;
    }

    /**
     * Sets the value of the goodsmvtSerialnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfBapi2017GmSerialnumber }
     *     
     */
    public void setGoodsmvtSerialnumber(TableOfBapi2017GmSerialnumber value) {
        this.goodsmvtSerialnumber = value;
    }

    /**
     * Gets the value of the goodsmvtServPartData property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfSpeBapi2017ServicepartData }
     *     
     */
    public TableOfSpeBapi2017ServicepartData getGoodsmvtServPartData() {
        return goodsmvtServPartData;
    }

    /**
     * Sets the value of the goodsmvtServPartData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfSpeBapi2017ServicepartData }
     *     
     */
    public void setGoodsmvtServPartData(TableOfSpeBapi2017ServicepartData value) {
        this.goodsmvtServPartData = value;
    }

    /**
     * Gets the value of the matdocumentyear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatdocumentyear() {
        return matdocumentyear;
    }

    /**
     * Sets the value of the matdocumentyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatdocumentyear(String value) {
        this.matdocumentyear = value;
    }

    /**
     * Gets the value of the materialdocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialdocument() {
        return materialdocument;
    }

    /**
     * Sets the value of the materialdocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialdocument(String value) {
        this.materialdocument = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfBapiret2 }
     *     
     */
    public TableOfBapiret2 getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfBapiret2 }
     *     
     */
    public void setReturn(TableOfBapiret2 value) {
        this._return = value;
    }

}
