//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.20 at 01:50:15 PM WIB 
//


package id.co.qualitas.domain.webservice.posto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.posto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.posto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMWBPOSTO }
     * 
     */
    public ZFMWBPOSTO createZFMWBPOSTO() {
        return new ZFMWBPOSTO();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBPOSTODETAIL }
     * 
     */
    public TABLEOFZTYWBPOSTODETAIL createTABLEOFZTYWBPOSTODETAIL() {
        return new TABLEOFZTYWBPOSTODETAIL();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBPOSTOHEADER }
     * 
     */
    public TABLEOFZTYWBPOSTOHEADER createTABLEOFZTYWBPOSTOHEADER() {
        return new TABLEOFZTYWBPOSTOHEADER();
    }

    /**
     * Create an instance of {@link ZFMWBPOSTOResponse }
     * 
     */
    public ZFMWBPOSTOResponse createZFMWBPOSTOResponse() {
        return new ZFMWBPOSTOResponse();
    }

    /**
     * Create an instance of {@link ZTYWBPOSTODETAIL }
     * 
     */
    public ZTYWBPOSTODETAIL createZTYWBPOSTODETAIL() {
        return new ZTYWBPOSTODETAIL();
    }

    /**
     * Create an instance of {@link ZTYWBPOSTOHEADER }
     * 
     */
    public ZTYWBPOSTOHEADER createZTYWBPOSTOHEADER() {
        return new ZTYWBPOSTOHEADER();
    }

}
