//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.20 at 01:50:15 PM WIB 
//


package id.co.qualitas.domain.webservice.posto;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZTY_WB_PO_STO_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZTY_WB_PO_STO_DETAIL"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ZDOCNO" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="POSNR" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="MATNR" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="TXZ01" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="MENGE" type="{urn:sap-com:document:sap:rfc:functions}quantum17.0"/&gt;
 *         &lt;element name="VBELN" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="ZPOSNR" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="UECHA" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="CHARG" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="VFDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="LFIMG" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="VRKME" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="MBLNR" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="BUDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZTY_WB_PO_STO_DETAIL", propOrder = {
    "zdocno",
    "posnr",
    "matnr",
    "txz01",
    "menge",
    "vbeln",
    "zposnr",
    "uecha",
    "charg",
    "vfdat",
    "lfimg",
    "vrkme",
    "mblnr",
    "budat"
})
public class ZTYWBPOSTODETAIL {

    @XmlElement(name = "ZDOCNO", required = true)
    protected String zdocno;
    @XmlElement(name = "POSNR", required = true)
    protected String posnr;
    @XmlElement(name = "MATNR", required = true)
    protected String matnr;
    @XmlElement(name = "TXZ01", required = true)
    protected String txz01;
    @XmlElement(name = "MENGE", required = true)
    protected BigDecimal menge;
    @XmlElement(name = "VBELN", required = true)
    protected String vbeln;
    @XmlElement(name = "ZPOSNR", required = true)
    protected String zposnr;
    @XmlElement(name = "UECHA", required = true)
    protected String uecha;
    @XmlElement(name = "CHARG", required = true)
    protected String charg;
    @XmlElement(name = "VFDAT", required = true)
    protected String vfdat;
    @XmlElement(name = "LFIMG", required = true)
    protected BigDecimal lfimg;
    @XmlElement(name = "VRKME", required = true)
    protected String vrkme;
    @XmlElement(name = "MBLNR", required = true)
    protected String mblnr;
    @XmlElement(name = "BUDAT", required = true)
    protected String budat;

    /**
     * Gets the value of the zdocno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZDOCNO() {
        return zdocno;
    }

    /**
     * Sets the value of the zdocno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZDOCNO(String value) {
        this.zdocno = value;
    }

    /**
     * Gets the value of the posnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSNR() {
        return posnr;
    }

    /**
     * Sets the value of the posnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSNR(String value) {
        this.posnr = value;
    }

    /**
     * Gets the value of the matnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATNR() {
        return matnr;
    }

    /**
     * Sets the value of the matnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATNR(String value) {
        this.matnr = value;
    }

    /**
     * Gets the value of the txz01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTXZ01() {
        return txz01;
    }

    /**
     * Sets the value of the txz01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTXZ01(String value) {
        this.txz01 = value;
    }

    /**
     * Gets the value of the menge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMENGE() {
        return menge;
    }

    /**
     * Sets the value of the menge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMENGE(BigDecimal value) {
        this.menge = value;
    }

    /**
     * Gets the value of the vbeln property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVBELN() {
        return vbeln;
    }

    /**
     * Sets the value of the vbeln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVBELN(String value) {
        this.vbeln = value;
    }

    /**
     * Gets the value of the zposnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZPOSNR() {
        return zposnr;
    }

    /**
     * Sets the value of the zposnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZPOSNR(String value) {
        this.zposnr = value;
    }

    /**
     * Gets the value of the uecha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUECHA() {
        return uecha;
    }

    /**
     * Sets the value of the uecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUECHA(String value) {
        this.uecha = value;
    }

    /**
     * Gets the value of the charg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHARG() {
        return charg;
    }

    /**
     * Sets the value of the charg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHARG(String value) {
        this.charg = value;
    }

    /**
     * Gets the value of the vfdat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVFDAT() {
        return vfdat;
    }

    /**
     * Sets the value of the vfdat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVFDAT(String value) {
        this.vfdat = value;
    }

    /**
     * Gets the value of the lfimg property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLFIMG() {
        return lfimg;
    }

    /**
     * Sets the value of the lfimg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLFIMG(BigDecimal value) {
        this.lfimg = value;
    }

    /**
     * Gets the value of the vrkme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVRKME() {
        return vrkme;
    }

    /**
     * Sets the value of the vrkme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVRKME(String value) {
        this.vrkme = value;
    }

    /**
     * Gets the value of the mblnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBLNR() {
        return mblnr;
    }

    /**
     * Sets the value of the mblnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBLNR(String value) {
        this.mblnr = value;
    }

    /**
     * Gets the value of the budat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUDAT() {
        return budat;
    }

    /**
     * Sets the value of the budat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUDAT(String value) {
        this.budat = value;
    }

}
