//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.25 at 09:48:40 AM WIB 
//


package id.co.qualitas.domain.webservice.podstatus;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.podstatus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.podstatus
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMWBPODSTATUS }
     * 
     */
    public ZFMWBPODSTATUS createZFMWBPODSTATUS() {
        return new ZFMWBPODSTATUS();
    }

    /**
     * Create an instance of {@link TABLEOFVBELNTAB }
     * 
     */
    public TABLEOFVBELNTAB createTABLEOFVBELNTAB() {
        return new TABLEOFVBELNTAB();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBPODSTATUS }
     * 
     */
    public TABLEOFZTYWBPODSTATUS createTABLEOFZTYWBPODSTATUS() {
        return new TABLEOFZTYWBPODSTATUS();
    }

    /**
     * Create an instance of {@link ZFMWBPODSTATUSResponse }
     * 
     */
    public ZFMWBPODSTATUSResponse createZFMWBPODSTATUSResponse() {
        return new ZFMWBPODSTATUSResponse();
    }

    /**
     * Create an instance of {@link ZTYWBPODSTATUS }
     * 
     */
    public ZTYWBPODSTATUS createZTYWBPODSTATUS() {
        return new ZTYWBPODSTATUS();
    }

    /**
     * Create an instance of {@link VBELNTAB }
     * 
     */
    public VBELNTAB createVBELNTAB() {
        return new VBELNTAB();
    }

}
