//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.25 at 09:48:40 AM WIB 
//


package id.co.qualitas.domain.webservice.podstatus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="INPUT" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_VBELN_TAB"/&gt;
 *         &lt;element name="RESULT" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZTY_WB_POD_STATUS" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "input",
    "result"
})
@XmlRootElement(name = "ZFM_WB_POD_STATUS")
public class ZFMWBPODSTATUS {

    @XmlElement(name = "INPUT", required = true)
    protected TABLEOFVBELNTAB input;
    @XmlElement(name = "RESULT")
    protected TABLEOFZTYWBPODSTATUS result;

    /**
     * Gets the value of the input property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFVBELNTAB }
     *     
     */
    public TABLEOFVBELNTAB getINPUT() {
        return input;
    }

    /**
     * Sets the value of the input property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFVBELNTAB }
     *     
     */
    public void setINPUT(TABLEOFVBELNTAB value) {
        this.input = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZTYWBPODSTATUS }
     *     
     */
    public TABLEOFZTYWBPODSTATUS getRESULT() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZTYWBPODSTATUS }
     *     
     */
    public void setRESULT(TABLEOFZTYWBPODSTATUS value) {
        this.result = value;
    }

}
