//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.25 at 09:48:40 AM WIB 
//


package id.co.qualitas.domain.webservice.podstatus;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZTY_WB_POD_STATUS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZTY_WB_POD_STATUS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VBELN" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="PDSTK" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="DESCR" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="MBLNR" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="T_WEIGHT" type="{urn:sap-com:document:sap:rfc:functions}quantum15.3"/&gt;
 *         &lt;element name="W_UOM" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="T_VOLUM" type="{urn:sap-com:document:sap:rfc:functions}quantum15.3"/&gt;
 *         &lt;element name="V_UOM" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZTY_WB_POD_STATUS", propOrder = {
    "vbeln",
    "pdstk",
    "descr",
    "mblnr",
    "tweight",
    "wuom",
    "tvolum",
    "vuom"
})
public class ZTYWBPODSTATUS {

    @XmlElement(name = "VBELN", required = true)
    protected String vbeln;
    @XmlElement(name = "PDSTK", required = true)
    protected String pdstk;
    @XmlElement(name = "DESCR", required = true)
    protected String descr;
    @XmlElement(name = "MBLNR", required = true)
    protected String mblnr;
    @XmlElement(name = "T_WEIGHT", required = true)
    protected BigDecimal tweight;
    @XmlElement(name = "W_UOM", required = true)
    protected String wuom;
    @XmlElement(name = "T_VOLUM", required = true)
    protected BigDecimal tvolum;
    @XmlElement(name = "V_UOM", required = true)
    protected String vuom;

    /**
     * Gets the value of the vbeln property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVBELN() {
        return vbeln;
    }

    /**
     * Sets the value of the vbeln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVBELN(String value) {
        this.vbeln = value;
    }

    /**
     * Gets the value of the pdstk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDSTK() {
        return pdstk;
    }

    /**
     * Sets the value of the pdstk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDSTK(String value) {
        this.pdstk = value;
    }

    /**
     * Gets the value of the descr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCR() {
        return descr;
    }

    /**
     * Sets the value of the descr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCR(String value) {
        this.descr = value;
    }

    /**
     * Gets the value of the mblnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBLNR() {
        return mblnr;
    }

    /**
     * Sets the value of the mblnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBLNR(String value) {
        this.mblnr = value;
    }

    /**
     * Gets the value of the tweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTWEIGHT() {
        return tweight;
    }

    /**
     * Sets the value of the tweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTWEIGHT(BigDecimal value) {
        this.tweight = value;
    }

    /**
     * Gets the value of the wuom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWUOM() {
        return wuom;
    }

    /**
     * Sets the value of the wuom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWUOM(String value) {
        this.wuom = value;
    }

    /**
     * Gets the value of the tvolum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTVOLUM() {
        return tvolum;
    }

    /**
     * Sets the value of the tvolum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTVOLUM(BigDecimal value) {
        this.tvolum = value;
    }

    /**
     * Gets the value of the vuom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVUOM() {
        return vuom;
    }

    /**
     * Sets the value of the vuom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVUOM(String value) {
        this.vuom = value;
    }

}
