//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.15 at 04:06:19 PM WIB 
//


package id.co.qualitas.domain.webservice.tposting;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.tposting package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.tposting
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMWBTP }
     * 
     */
    public ZFMWBTP createZFMWBTP() {
        return new ZFMWBTP();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBTPDETAIL }
     * 
     */
    public TABLEOFZTYWBTPDETAIL createTABLEOFZTYWBTPDETAIL() {
        return new TABLEOFZTYWBTPDETAIL();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBTPHEADER }
     * 
     */
    public TABLEOFZTYWBTPHEADER createTABLEOFZTYWBTPHEADER() {
        return new TABLEOFZTYWBTPHEADER();
    }

    /**
     * Create an instance of {@link ZFMWBTPResponse }
     * 
     */
    public ZFMWBTPResponse createZFMWBTPResponse() {
        return new ZFMWBTPResponse();
    }

    /**
     * Create an instance of {@link ZTYWBTPDETAIL }
     * 
     */
    public ZTYWBTPDETAIL createZTYWBTPDETAIL() {
        return new ZTYWBTPDETAIL();
    }

    /**
     * Create an instance of {@link ZTYWBTPHEADER }
     * 
     */
    public ZTYWBTPHEADER createZTYWBTPHEADER() {
        return new ZTYWBTPHEADER();
    }

}
