//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.15 at 04:06:19 PM WIB 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:sap-com:document:sap:rfc:functions")
package id.co.qualitas.domain.webservice.tposting;
