//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 12:24:04 PM WIB 
//


package id.co.qualitas.domain.webservice.pofg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="COMPONENT" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZTY_WB_POFG_COMPONENT"/&gt;
 *         &lt;element name="DETAIL" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZTY_WB_POFG_DETAIL"/&gt;
 *         &lt;element name="HEADER" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZTY_WB_POFG_HEADER"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "component",
    "detail",
    "header"
})
@XmlRootElement(name = "ZFM_WB_POFGResponse")
public class ZFMWBPOFGResponse {

    @XmlElement(name = "COMPONENT", required = true)
    protected TABLEOFZTYWBPOFGCOMPONENT component;
    @XmlElement(name = "DETAIL", required = true)
    protected TABLEOFZTYWBPOFGDETAIL detail;
    @XmlElement(name = "HEADER", required = true)
    protected TABLEOFZTYWBPOFGHEADER header;

    /**
     * Gets the value of the component property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZTYWBPOFGCOMPONENT }
     *     
     */
    public TABLEOFZTYWBPOFGCOMPONENT getCOMPONENT() {
        return component;
    }

    /**
     * Sets the value of the component property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZTYWBPOFGCOMPONENT }
     *     
     */
    public void setCOMPONENT(TABLEOFZTYWBPOFGCOMPONENT value) {
        this.component = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZTYWBPOFGDETAIL }
     *     
     */
    public TABLEOFZTYWBPOFGDETAIL getDETAIL() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZTYWBPOFGDETAIL }
     *     
     */
    public void setDETAIL(TABLEOFZTYWBPOFGDETAIL value) {
        this.detail = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZTYWBPOFGHEADER }
     *     
     */
    public TABLEOFZTYWBPOFGHEADER getHEADER() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZTYWBPOFGHEADER }
     *     
     */
    public void setHEADER(TABLEOFZTYWBPOFGHEADER value) {
        this.header = value;
    }

}
