//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.20 at 04:11:48 PM WIB 
//


package id.co.qualitas.domain.webservice.plant;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.plant package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.plant
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMWBPLANT }
     * 
     */
    public ZFMWBPLANT createZFMWBPLANT() {
        return new ZFMWBPLANT();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBPLANT }
     * 
     */
    public TABLEOFZTYWBPLANT createTABLEOFZTYWBPLANT() {
        return new TABLEOFZTYWBPLANT();
    }

    /**
     * Create an instance of {@link ZFMWBPLANTResponse }
     * 
     */
    public ZFMWBPLANTResponse createZFMWBPLANTResponse() {
        return new ZFMWBPLANTResponse();
    }

    /**
     * Create an instance of {@link ZTYWBPLANT }
     * 
     */
    public ZTYWBPLANT createZTYWBPLANT() {
        return new ZTYWBPLANT();
    }

}
