//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.04 at 10:46:32 AM WIB 
//


package id.co.qualitas.domain.webservice.shipmentchange;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BAPISHIPMENTHEADER complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPISHIPMENTHEADER"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SHIPMENT_NUM" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="GUID" type="{urn:sap-com:document:sap:rfc:functions}char22"/&gt;
 *         &lt;element name="SHIPMENT_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="TRANS_PLAN_PT" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="SERVICE_LEVEL" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="SHIPPING_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="SHIPPING_TYPE_PRE_LEG" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="SHIPPING_TYPE_SUB_LEG" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="SHIPPING_COND" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="SHIPMENT_ROUTE" type="{urn:sap-com:document:sap:rfc:functions}char6"/&gt;
 *         &lt;element name="CONTAINER_ID" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="EXTERNAL_ID_1" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="EXTERNAL_ID_2" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="DESCRIPTION" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="STATUS_PLAN" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="STATUS_CHECKIN" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="STATUS_LOAD_START" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="STATUS_LOAD_END" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="STATUS_COMPL" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="STATUS_SHPMNT_START" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="STATUS_SHPMNT_END" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="SERVICE_AGENT_ID" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="DISTANCE" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="DISTANCE_UNIT" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="DISTANCE_UNIT_ISO" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="TIME_TRAVEL" type="{urn:sap-com:document:sap:rfc:functions}decimal11.0"/&gt;
 *         &lt;element name="TIME_TOTAL" type="{urn:sap-com:document:sap:rfc:functions}decimal11.0"/&gt;
 *         &lt;element name="TIME_UNIT" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="TIME_UNIT_ISO" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="PRICING_PROCEDURE" type="{urn:sap-com:document:sap:rfc:functions}char6"/&gt;
 *         &lt;element name="SPECIAL_PROCEDURE_ID" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="SHPMNT_COST_REL" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="TIME_TOTAL_PLAN" type="{urn:sap-com:document:sap:rfc:functions}decimal11.0"/&gt;
 *         &lt;element name="TIME_DURATION_PLAN" type="{urn:sap-com:document:sap:rfc:functions}decimal11.0"/&gt;
 *         &lt;element name="TIME_TOTAL_ACT" type="{urn:sap-com:document:sap:rfc:functions}decimal11.0"/&gt;
 *         &lt;element name="TIME_DURATION_ACT" type="{urn:sap-com:document:sap:rfc:functions}decimal11.0"/&gt;
 *         &lt;element name="SUPPL_1" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="SUPPL_2" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="SUPPL_3" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="SUPPL_4" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="TEXT_1" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="TEXT_2" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="TEXT_3" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="TEXT_4" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="DG_GOOD_PROFILE" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="TIME_WAIT_PLAN" type="{urn:sap-com:document:sap:rfc:functions}decimal11.0"/&gt;
 *         &lt;element name="TIME_WAIT_ACT" type="{urn:sap-com:document:sap:rfc:functions}decimal11.0"/&gt;
 *         &lt;element name="ROUTE_SCHEDULE" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="STATUS_TENDERING" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="TENDERING_ACCREJ_REASON" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="TENDERING_TEXT" type="{urn:sap-com:document:sap:rfc:functions}char80"/&gt;
 *         &lt;element name="TENDERING_MAX_PRICE" type="{urn:sap-com:document:sap:rfc:functions}curr15.2"/&gt;
 *         &lt;element name="TENDERING_MP_CURR_UNIT" type="{urn:sap-com:document:sap:rfc:functions}cuky5"/&gt;
 *         &lt;element name="TENDERING_MP_CURR_UNIT_ISO" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="TENDERING_ACT_PRICE" type="{urn:sap-com:document:sap:rfc:functions}curr15.2"/&gt;
 *         &lt;element name="TENDERING_AP_CURR_UNIT" type="{urn:sap-com:document:sap:rfc:functions}cuky5"/&gt;
 *         &lt;element name="TENDERING_AP_CURR_UNIT_ISO" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="TENDERING_CARRIER_ID" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="TENDERING_CARRIER_NAME" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="TENDERING_CARRIER_TRACK_ID" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="TENDERING_OFFER_DATE" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="TENDERING_OFFER_TIME" type="{urn:sap-com:document:sap:rfc:functions}time"/&gt;
 *         &lt;element name="TENDERING_LOAD_LENGTH" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="TENDERING_LL_UNIT" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="TENDERING_LL_UNIT_ISO" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPISHIPMENTHEADER", propOrder = {
    "shipmentnum",
    "guid",
    "shipmenttype",
    "transplanpt",
    "servicelevel",
    "shippingtype",
    "shippingtypepreleg",
    "shippingtypesubleg",
    "shippingcond",
    "shipmentroute",
    "containerid",
    "externalid1",
    "externalid2",
    "description",
    "statusplan",
    "statuscheckin",
    "statusloadstart",
    "statusloadend",
    "statuscompl",
    "statusshpmntstart",
    "statusshpmntend",
    "serviceagentid",
    "distance",
    "distanceunit",
    "distanceunitiso",
    "timetravel",
    "timetotal",
    "timeunit",
    "timeunitiso",
    "pricingprocedure",
    "specialprocedureid",
    "shpmntcostrel",
    "timetotalplan",
    "timedurationplan",
    "timetotalact",
    "timedurationact",
    "suppl1",
    "suppl2",
    "suppl3",
    "suppl4",
    "text1",
    "text2",
    "text3",
    "text4",
    "dggoodprofile",
    "timewaitplan",
    "timewaitact",
    "routeschedule",
    "statustendering",
    "tenderingaccrejreason",
    "tenderingtext",
    "tenderingmaxprice",
    "tenderingmpcurrunit",
    "tenderingmpcurrunitiso",
    "tenderingactprice",
    "tenderingapcurrunit",
    "tenderingapcurrunitiso",
    "tenderingcarrierid",
    "tenderingcarriername",
    "tenderingcarriertrackid",
    "tenderingofferdate",
    "tenderingoffertime",
    "tenderingloadlength",
    "tenderingllunit",
    "tenderingllunitiso"
})
public class BAPISHIPMENTHEADER {

    @XmlElement(name = "SHIPMENT_NUM", required = true)
    protected String shipmentnum;
    @XmlElement(name = "GUID", required = true)
    protected String guid;
    @XmlElement(name = "SHIPMENT_TYPE", required = true)
    protected String shipmenttype;
    @XmlElement(name = "TRANS_PLAN_PT", required = true)
    protected String transplanpt;
    @XmlElement(name = "SERVICE_LEVEL", required = true)
    protected String servicelevel;
    @XmlElement(name = "SHIPPING_TYPE", required = true)
    protected String shippingtype;
    @XmlElement(name = "SHIPPING_TYPE_PRE_LEG", required = true)
    protected String shippingtypepreleg;
    @XmlElement(name = "SHIPPING_TYPE_SUB_LEG", required = true)
    protected String shippingtypesubleg;
    @XmlElement(name = "SHIPPING_COND", required = true)
    protected String shippingcond;
    @XmlElement(name = "SHIPMENT_ROUTE", required = true)
    protected String shipmentroute;
    @XmlElement(name = "CONTAINER_ID", required = true)
    protected String containerid;
    @XmlElement(name = "EXTERNAL_ID_1", required = true)
    protected String externalid1;
    @XmlElement(name = "EXTERNAL_ID_2", required = true)
    protected String externalid2;
    @XmlElement(name = "DESCRIPTION", required = true)
    protected String description;
    @XmlElement(name = "STATUS_PLAN", required = true)
    protected String statusplan;
    @XmlElement(name = "STATUS_CHECKIN", required = true)
    protected String statuscheckin;
    @XmlElement(name = "STATUS_LOAD_START", required = true)
    protected String statusloadstart;
    @XmlElement(name = "STATUS_LOAD_END", required = true)
    protected String statusloadend;
    @XmlElement(name = "STATUS_COMPL", required = true)
    protected String statuscompl;
    @XmlElement(name = "STATUS_SHPMNT_START", required = true)
    protected String statusshpmntstart;
    @XmlElement(name = "STATUS_SHPMNT_END", required = true)
    protected String statusshpmntend;
    @XmlElement(name = "SERVICE_AGENT_ID", required = true)
    protected String serviceagentid;
    @XmlElement(name = "DISTANCE", required = true)
    protected BigDecimal distance;
    @XmlElement(name = "DISTANCE_UNIT", required = true)
    protected String distanceunit;
    @XmlElement(name = "DISTANCE_UNIT_ISO", required = true)
    protected String distanceunitiso;
    @XmlElement(name = "TIME_TRAVEL", required = true)
    protected BigDecimal timetravel;
    @XmlElement(name = "TIME_TOTAL", required = true)
    protected BigDecimal timetotal;
    @XmlElement(name = "TIME_UNIT", required = true)
    protected String timeunit;
    @XmlElement(name = "TIME_UNIT_ISO", required = true)
    protected String timeunitiso;
    @XmlElement(name = "PRICING_PROCEDURE", required = true)
    protected String pricingprocedure;
    @XmlElement(name = "SPECIAL_PROCEDURE_ID", required = true)
    protected String specialprocedureid;
    @XmlElement(name = "SHPMNT_COST_REL", required = true)
    protected String shpmntcostrel;
    @XmlElement(name = "TIME_TOTAL_PLAN", required = true)
    protected BigDecimal timetotalplan;
    @XmlElement(name = "TIME_DURATION_PLAN", required = true)
    protected BigDecimal timedurationplan;
    @XmlElement(name = "TIME_TOTAL_ACT", required = true)
    protected BigDecimal timetotalact;
    @XmlElement(name = "TIME_DURATION_ACT", required = true)
    protected BigDecimal timedurationact;
    @XmlElement(name = "SUPPL_1", required = true)
    protected String suppl1;
    @XmlElement(name = "SUPPL_2", required = true)
    protected String suppl2;
    @XmlElement(name = "SUPPL_3", required = true)
    protected String suppl3;
    @XmlElement(name = "SUPPL_4", required = true)
    protected String suppl4;
    @XmlElement(name = "TEXT_1", required = true)
    protected String text1;
    @XmlElement(name = "TEXT_2", required = true)
    protected String text2;
    @XmlElement(name = "TEXT_3", required = true)
    protected String text3;
    @XmlElement(name = "TEXT_4", required = true)
    protected String text4;
    @XmlElement(name = "DG_GOOD_PROFILE", required = true)
    protected String dggoodprofile;
    @XmlElement(name = "TIME_WAIT_PLAN", required = true)
    protected BigDecimal timewaitplan;
    @XmlElement(name = "TIME_WAIT_ACT", required = true)
    protected BigDecimal timewaitact;
    @XmlElement(name = "ROUTE_SCHEDULE", required = true)
    protected String routeschedule;
    @XmlElement(name = "STATUS_TENDERING", required = true)
    protected String statustendering;
    @XmlElement(name = "TENDERING_ACCREJ_REASON", required = true)
    protected String tenderingaccrejreason;
    @XmlElement(name = "TENDERING_TEXT", required = true)
    protected String tenderingtext;
    @XmlElement(name = "TENDERING_MAX_PRICE", required = true)
    protected BigDecimal tenderingmaxprice;
    @XmlElement(name = "TENDERING_MP_CURR_UNIT", required = true)
    protected String tenderingmpcurrunit;
    @XmlElement(name = "TENDERING_MP_CURR_UNIT_ISO", required = true)
    protected String tenderingmpcurrunitiso;
    @XmlElement(name = "TENDERING_ACT_PRICE", required = true)
    protected BigDecimal tenderingactprice;
    @XmlElement(name = "TENDERING_AP_CURR_UNIT", required = true)
    protected String tenderingapcurrunit;
    @XmlElement(name = "TENDERING_AP_CURR_UNIT_ISO", required = true)
    protected String tenderingapcurrunitiso;
    @XmlElement(name = "TENDERING_CARRIER_ID", required = true)
    protected String tenderingcarrierid;
    @XmlElement(name = "TENDERING_CARRIER_NAME", required = true)
    protected String tenderingcarriername;
    @XmlElement(name = "TENDERING_CARRIER_TRACK_ID", required = true)
    protected String tenderingcarriertrackid;
    @XmlElement(name = "TENDERING_OFFER_DATE", required = true)
    protected String tenderingofferdate;
    @XmlElement(name = "TENDERING_OFFER_TIME", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar tenderingoffertime;
    @XmlElement(name = "TENDERING_LOAD_LENGTH", required = true)
    protected BigDecimal tenderingloadlength;
    @XmlElement(name = "TENDERING_LL_UNIT", required = true)
    protected String tenderingllunit;
    @XmlElement(name = "TENDERING_LL_UNIT_ISO", required = true)
    protected String tenderingllunitiso;

    /**
     * Gets the value of the shipmentnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPMENTNUM() {
        return shipmentnum;
    }

    /**
     * Sets the value of the shipmentnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPMENTNUM(String value) {
        this.shipmentnum = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGUID() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGUID(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the shipmenttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPMENTTYPE() {
        return shipmenttype;
    }

    /**
     * Sets the value of the shipmenttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPMENTTYPE(String value) {
        this.shipmenttype = value;
    }

    /**
     * Gets the value of the transplanpt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSPLANPT() {
        return transplanpt;
    }

    /**
     * Sets the value of the transplanpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSPLANPT(String value) {
        this.transplanpt = value;
    }

    /**
     * Gets the value of the servicelevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVICELEVEL() {
        return servicelevel;
    }

    /**
     * Sets the value of the servicelevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVICELEVEL(String value) {
        this.servicelevel = value;
    }

    /**
     * Gets the value of the shippingtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPPINGTYPE() {
        return shippingtype;
    }

    /**
     * Sets the value of the shippingtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPPINGTYPE(String value) {
        this.shippingtype = value;
    }

    /**
     * Gets the value of the shippingtypepreleg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPPINGTYPEPRELEG() {
        return shippingtypepreleg;
    }

    /**
     * Sets the value of the shippingtypepreleg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPPINGTYPEPRELEG(String value) {
        this.shippingtypepreleg = value;
    }

    /**
     * Gets the value of the shippingtypesubleg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPPINGTYPESUBLEG() {
        return shippingtypesubleg;
    }

    /**
     * Sets the value of the shippingtypesubleg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPPINGTYPESUBLEG(String value) {
        this.shippingtypesubleg = value;
    }

    /**
     * Gets the value of the shippingcond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPPINGCOND() {
        return shippingcond;
    }

    /**
     * Sets the value of the shippingcond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPPINGCOND(String value) {
        this.shippingcond = value;
    }

    /**
     * Gets the value of the shipmentroute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPMENTROUTE() {
        return shipmentroute;
    }

    /**
     * Sets the value of the shipmentroute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPMENTROUTE(String value) {
        this.shipmentroute = value;
    }

    /**
     * Gets the value of the containerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTAINERID() {
        return containerid;
    }

    /**
     * Sets the value of the containerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTAINERID(String value) {
        this.containerid = value;
    }

    /**
     * Gets the value of the externalid1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTERNALID1() {
        return externalid1;
    }

    /**
     * Sets the value of the externalid1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTERNALID1(String value) {
        this.externalid1 = value;
    }

    /**
     * Gets the value of the externalid2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTERNALID2() {
        return externalid2;
    }

    /**
     * Sets the value of the externalid2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTERNALID2(String value) {
        this.externalid2 = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the statusplan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSPLAN() {
        return statusplan;
    }

    /**
     * Sets the value of the statusplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSPLAN(String value) {
        this.statusplan = value;
    }

    /**
     * Gets the value of the statuscheckin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSCHECKIN() {
        return statuscheckin;
    }

    /**
     * Sets the value of the statuscheckin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSCHECKIN(String value) {
        this.statuscheckin = value;
    }

    /**
     * Gets the value of the statusloadstart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSLOADSTART() {
        return statusloadstart;
    }

    /**
     * Sets the value of the statusloadstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSLOADSTART(String value) {
        this.statusloadstart = value;
    }

    /**
     * Gets the value of the statusloadend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSLOADEND() {
        return statusloadend;
    }

    /**
     * Sets the value of the statusloadend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSLOADEND(String value) {
        this.statusloadend = value;
    }

    /**
     * Gets the value of the statuscompl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSCOMPL() {
        return statuscompl;
    }

    /**
     * Sets the value of the statuscompl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSCOMPL(String value) {
        this.statuscompl = value;
    }

    /**
     * Gets the value of the statusshpmntstart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSSHPMNTSTART() {
        return statusshpmntstart;
    }

    /**
     * Sets the value of the statusshpmntstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSSHPMNTSTART(String value) {
        this.statusshpmntstart = value;
    }

    /**
     * Gets the value of the statusshpmntend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSSHPMNTEND() {
        return statusshpmntend;
    }

    /**
     * Sets the value of the statusshpmntend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSSHPMNTEND(String value) {
        this.statusshpmntend = value;
    }

    /**
     * Gets the value of the serviceagentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVICEAGENTID() {
        return serviceagentid;
    }

    /**
     * Sets the value of the serviceagentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVICEAGENTID(String value) {
        this.serviceagentid = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDISTANCE() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDISTANCE(BigDecimal value) {
        this.distance = value;
    }

    /**
     * Gets the value of the distanceunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISTANCEUNIT() {
        return distanceunit;
    }

    /**
     * Sets the value of the distanceunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISTANCEUNIT(String value) {
        this.distanceunit = value;
    }

    /**
     * Gets the value of the distanceunitiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISTANCEUNITISO() {
        return distanceunitiso;
    }

    /**
     * Sets the value of the distanceunitiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISTANCEUNITISO(String value) {
        this.distanceunitiso = value;
    }

    /**
     * Gets the value of the timetravel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTIMETRAVEL() {
        return timetravel;
    }

    /**
     * Sets the value of the timetravel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTIMETRAVEL(BigDecimal value) {
        this.timetravel = value;
    }

    /**
     * Gets the value of the timetotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTIMETOTAL() {
        return timetotal;
    }

    /**
     * Sets the value of the timetotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTIMETOTAL(BigDecimal value) {
        this.timetotal = value;
    }

    /**
     * Gets the value of the timeunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEUNIT() {
        return timeunit;
    }

    /**
     * Sets the value of the timeunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEUNIT(String value) {
        this.timeunit = value;
    }

    /**
     * Gets the value of the timeunitiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEUNITISO() {
        return timeunitiso;
    }

    /**
     * Sets the value of the timeunitiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEUNITISO(String value) {
        this.timeunitiso = value;
    }

    /**
     * Gets the value of the pricingprocedure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRICINGPROCEDURE() {
        return pricingprocedure;
    }

    /**
     * Sets the value of the pricingprocedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRICINGPROCEDURE(String value) {
        this.pricingprocedure = value;
    }

    /**
     * Gets the value of the specialprocedureid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPECIALPROCEDUREID() {
        return specialprocedureid;
    }

    /**
     * Sets the value of the specialprocedureid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPECIALPROCEDUREID(String value) {
        this.specialprocedureid = value;
    }

    /**
     * Gets the value of the shpmntcostrel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHPMNTCOSTREL() {
        return shpmntcostrel;
    }

    /**
     * Sets the value of the shpmntcostrel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHPMNTCOSTREL(String value) {
        this.shpmntcostrel = value;
    }

    /**
     * Gets the value of the timetotalplan property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTIMETOTALPLAN() {
        return timetotalplan;
    }

    /**
     * Sets the value of the timetotalplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTIMETOTALPLAN(BigDecimal value) {
        this.timetotalplan = value;
    }

    /**
     * Gets the value of the timedurationplan property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTIMEDURATIONPLAN() {
        return timedurationplan;
    }

    /**
     * Sets the value of the timedurationplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTIMEDURATIONPLAN(BigDecimal value) {
        this.timedurationplan = value;
    }

    /**
     * Gets the value of the timetotalact property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTIMETOTALACT() {
        return timetotalact;
    }

    /**
     * Sets the value of the timetotalact property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTIMETOTALACT(BigDecimal value) {
        this.timetotalact = value;
    }

    /**
     * Gets the value of the timedurationact property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTIMEDURATIONACT() {
        return timedurationact;
    }

    /**
     * Sets the value of the timedurationact property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTIMEDURATIONACT(BigDecimal value) {
        this.timedurationact = value;
    }

    /**
     * Gets the value of the suppl1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPL1() {
        return suppl1;
    }

    /**
     * Sets the value of the suppl1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPL1(String value) {
        this.suppl1 = value;
    }

    /**
     * Gets the value of the suppl2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPL2() {
        return suppl2;
    }

    /**
     * Sets the value of the suppl2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPL2(String value) {
        this.suppl2 = value;
    }

    /**
     * Gets the value of the suppl3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPL3() {
        return suppl3;
    }

    /**
     * Sets the value of the suppl3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPL3(String value) {
        this.suppl3 = value;
    }

    /**
     * Gets the value of the suppl4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPL4() {
        return suppl4;
    }

    /**
     * Sets the value of the suppl4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPL4(String value) {
        this.suppl4 = value;
    }

    /**
     * Gets the value of the text1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT1() {
        return text1;
    }

    /**
     * Sets the value of the text1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT1(String value) {
        this.text1 = value;
    }

    /**
     * Gets the value of the text2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT2() {
        return text2;
    }

    /**
     * Sets the value of the text2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT2(String value) {
        this.text2 = value;
    }

    /**
     * Gets the value of the text3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT3() {
        return text3;
    }

    /**
     * Sets the value of the text3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT3(String value) {
        this.text3 = value;
    }

    /**
     * Gets the value of the text4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT4() {
        return text4;
    }

    /**
     * Sets the value of the text4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT4(String value) {
        this.text4 = value;
    }

    /**
     * Gets the value of the dggoodprofile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDGGOODPROFILE() {
        return dggoodprofile;
    }

    /**
     * Sets the value of the dggoodprofile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDGGOODPROFILE(String value) {
        this.dggoodprofile = value;
    }

    /**
     * Gets the value of the timewaitplan property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTIMEWAITPLAN() {
        return timewaitplan;
    }

    /**
     * Sets the value of the timewaitplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTIMEWAITPLAN(BigDecimal value) {
        this.timewaitplan = value;
    }

    /**
     * Gets the value of the timewaitact property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTIMEWAITACT() {
        return timewaitact;
    }

    /**
     * Sets the value of the timewaitact property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTIMEWAITACT(BigDecimal value) {
        this.timewaitact = value;
    }

    /**
     * Gets the value of the routeschedule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROUTESCHEDULE() {
        return routeschedule;
    }

    /**
     * Sets the value of the routeschedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROUTESCHEDULE(String value) {
        this.routeschedule = value;
    }

    /**
     * Gets the value of the statustendering property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSTENDERING() {
        return statustendering;
    }

    /**
     * Sets the value of the statustendering property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSTENDERING(String value) {
        this.statustendering = value;
    }

    /**
     * Gets the value of the tenderingaccrejreason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGACCREJREASON() {
        return tenderingaccrejreason;
    }

    /**
     * Sets the value of the tenderingaccrejreason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGACCREJREASON(String value) {
        this.tenderingaccrejreason = value;
    }

    /**
     * Gets the value of the tenderingtext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGTEXT() {
        return tenderingtext;
    }

    /**
     * Sets the value of the tenderingtext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGTEXT(String value) {
        this.tenderingtext = value;
    }

    /**
     * Gets the value of the tenderingmaxprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTENDERINGMAXPRICE() {
        return tenderingmaxprice;
    }

    /**
     * Sets the value of the tenderingmaxprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTENDERINGMAXPRICE(BigDecimal value) {
        this.tenderingmaxprice = value;
    }

    /**
     * Gets the value of the tenderingmpcurrunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGMPCURRUNIT() {
        return tenderingmpcurrunit;
    }

    /**
     * Sets the value of the tenderingmpcurrunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGMPCURRUNIT(String value) {
        this.tenderingmpcurrunit = value;
    }

    /**
     * Gets the value of the tenderingmpcurrunitiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGMPCURRUNITISO() {
        return tenderingmpcurrunitiso;
    }

    /**
     * Sets the value of the tenderingmpcurrunitiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGMPCURRUNITISO(String value) {
        this.tenderingmpcurrunitiso = value;
    }

    /**
     * Gets the value of the tenderingactprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTENDERINGACTPRICE() {
        return tenderingactprice;
    }

    /**
     * Sets the value of the tenderingactprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTENDERINGACTPRICE(BigDecimal value) {
        this.tenderingactprice = value;
    }

    /**
     * Gets the value of the tenderingapcurrunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGAPCURRUNIT() {
        return tenderingapcurrunit;
    }

    /**
     * Sets the value of the tenderingapcurrunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGAPCURRUNIT(String value) {
        this.tenderingapcurrunit = value;
    }

    /**
     * Gets the value of the tenderingapcurrunitiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGAPCURRUNITISO() {
        return tenderingapcurrunitiso;
    }

    /**
     * Sets the value of the tenderingapcurrunitiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGAPCURRUNITISO(String value) {
        this.tenderingapcurrunitiso = value;
    }

    /**
     * Gets the value of the tenderingcarrierid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGCARRIERID() {
        return tenderingcarrierid;
    }

    /**
     * Sets the value of the tenderingcarrierid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGCARRIERID(String value) {
        this.tenderingcarrierid = value;
    }

    /**
     * Gets the value of the tenderingcarriername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGCARRIERNAME() {
        return tenderingcarriername;
    }

    /**
     * Sets the value of the tenderingcarriername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGCARRIERNAME(String value) {
        this.tenderingcarriername = value;
    }

    /**
     * Gets the value of the tenderingcarriertrackid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGCARRIERTRACKID() {
        return tenderingcarriertrackid;
    }

    /**
     * Sets the value of the tenderingcarriertrackid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGCARRIERTRACKID(String value) {
        this.tenderingcarriertrackid = value;
    }

    /**
     * Gets the value of the tenderingofferdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGOFFERDATE() {
        return tenderingofferdate;
    }

    /**
     * Sets the value of the tenderingofferdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGOFFERDATE(String value) {
        this.tenderingofferdate = value;
    }

    /**
     * Gets the value of the tenderingoffertime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTENDERINGOFFERTIME() {
        return tenderingoffertime;
    }

    /**
     * Sets the value of the tenderingoffertime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTENDERINGOFFERTIME(XMLGregorianCalendar value) {
        this.tenderingoffertime = value;
    }

    /**
     * Gets the value of the tenderingloadlength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTENDERINGLOADLENGTH() {
        return tenderingloadlength;
    }

    /**
     * Sets the value of the tenderingloadlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTENDERINGLOADLENGTH(BigDecimal value) {
        this.tenderingloadlength = value;
    }

    /**
     * Gets the value of the tenderingllunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGLLUNIT() {
        return tenderingllunit;
    }

    /**
     * Sets the value of the tenderingllunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGLLUNIT(String value) {
        this.tenderingllunit = value;
    }

    /**
     * Gets the value of the tenderingllunitiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERINGLLUNITISO() {
        return tenderingllunitiso;
    }

    /**
     * Sets the value of the tenderingllunitiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERINGLLUNITISO(String value) {
        this.tenderingllunitiso = value;
    }

}
