//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.04 at 10:46:32 AM WIB 
//


package id.co.qualitas.domain.webservice.shipmentchange;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.shipmentchange package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.shipmentchange
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMSHIPMENTCHANGE }
     * 
     */
    public ZFMSHIPMENTCHANGE createZFMSHIPMENTCHANGE() {
        return new ZFMSHIPMENTCHANGE();
    }

    /**
     * Create an instance of {@link BAPISHIPMENTHEADER }
     * 
     */
    public BAPISHIPMENTHEADER createBAPISHIPMENTHEADER() {
        return new BAPISHIPMENTHEADER();
    }

    /**
     * Create an instance of {@link BAPISHIPMENTHEADERACTION }
     * 
     */
    public BAPISHIPMENTHEADERACTION createBAPISHIPMENTHEADERACTION() {
        return new BAPISHIPMENTHEADERACTION();
    }

    /**
     * Create an instance of {@link TABLEOFBAPISHIPMENTITEM }
     * 
     */
    public TABLEOFBAPISHIPMENTITEM createTABLEOFBAPISHIPMENTITEM() {
        return new TABLEOFBAPISHIPMENTITEM();
    }

    /**
     * Create an instance of {@link TABLEOFBAPISHIPMENTITEMACTION }
     * 
     */
    public TABLEOFBAPISHIPMENTITEMACTION createTABLEOFBAPISHIPMENTITEMACTION() {
        return new TABLEOFBAPISHIPMENTITEMACTION();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBSHIPMENTCHANGE }
     * 
     */
    public TABLEOFZTYWBSHIPMENTCHANGE createTABLEOFZTYWBSHIPMENTCHANGE() {
        return new TABLEOFZTYWBSHIPMENTCHANGE();
    }

    /**
     * Create an instance of {@link TABLEOFBAPIRET2 }
     * 
     */
    public TABLEOFBAPIRET2 createTABLEOFBAPIRET2() {
        return new TABLEOFBAPIRET2();
    }

    /**
     * Create an instance of {@link ZFMSHIPMENTCHANGEResponse }
     * 
     */
    public ZFMSHIPMENTCHANGEResponse createZFMSHIPMENTCHANGEResponse() {
        return new ZFMSHIPMENTCHANGEResponse();
    }

    /**
     * Create an instance of {@link BAPISHIPMENTITEMACTION }
     * 
     */
    public BAPISHIPMENTITEMACTION createBAPISHIPMENTITEMACTION() {
        return new BAPISHIPMENTITEMACTION();
    }

    /**
     * Create an instance of {@link ZTYWBSHIPMENTCHANGE }
     * 
     */
    public ZTYWBSHIPMENTCHANGE createZTYWBSHIPMENTCHANGE() {
        return new ZTYWBSHIPMENTCHANGE();
    }

    /**
     * Create an instance of {@link BAPISHIPMENTITEM }
     * 
     */
    public BAPISHIPMENTITEM createBAPISHIPMENTITEM() {
        return new BAPISHIPMENTITEM();
    }

    /**
     * Create an instance of {@link BAPIRET2 }
     * 
     */
    public BAPIRET2 createBAPIRET2() {
        return new BAPIRET2();
    }

}
