//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.19 at 05:37:38 PM WIB 
//


package id.co.qualitas.domain.webservice.material;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.material package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.material
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMWBMATNR }
     * 
     */
    public ZFMWBMATNR createZFMWBMATNR() {
        return new ZFMWBMATNR();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBMATNR }
     * 
     */
    public TABLEOFZTYWBMATNR createTABLEOFZTYWBMATNR() {
        return new TABLEOFZTYWBMATNR();
    }

    /**
     * Create an instance of {@link ZFMWBMATNRResponse }
     * 
     */
    public ZFMWBMATNRResponse createZFMWBMATNRResponse() {
        return new ZFMWBMATNRResponse();
    }

    /**
     * Create an instance of {@link ZTYWBMATNR }
     * 
     */
    public ZTYWBMATNR createZTYWBMATNR() {
        return new ZTYWBMATNR();
    }

}
