//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.19 at 05:37:38 PM WIB 
//


package id.co.qualitas.domain.webservice.material;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="P_MATNR" type="{urn:sap-com:document:sap:rfc:functions}char18" minOccurs="0"/&gt;
 *         &lt;element name="RESULT" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZTY_WB_MATNR"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pmatnr",
    "result"
})
@XmlRootElement(name = "ZFM_WB_MATNR")
public class ZFMWBMATNR {

    @XmlElement(name = "P_MATNR")
    protected String pmatnr;
    @XmlElement(name = "RESULT", required = true)
    protected TABLEOFZTYWBMATNR result;

    /**
     * Gets the value of the pmatnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPMATNR() {
        return pmatnr;
    }

    /**
     * Sets the value of the pmatnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPMATNR(String value) {
        this.pmatnr = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZTYWBMATNR }
     *     
     */
    public TABLEOFZTYWBMATNR getRESULT() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZTYWBMATNR }
     *     
     */
    public void setRESULT(TABLEOFZTYWBMATNR value) {
        this.result = value;
    }

}
