//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 05:42:42 PM WIB 
//


package id.co.qualitas.domain.webservice.postoso;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.postoso package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.postoso
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMWBPOSTOSO }
     * 
     */
    public ZFMWBPOSTOSO createZFMWBPOSTOSO() {
        return new ZFMWBPOSTOSO();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBPOSTOSODETAIL }
     * 
     */
    public TABLEOFZTYWBPOSTOSODETAIL createTABLEOFZTYWBPOSTOSODETAIL() {
        return new TABLEOFZTYWBPOSTOSODETAIL();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBPOSTOSOHEADER }
     * 
     */
    public TABLEOFZTYWBPOSTOSOHEADER createTABLEOFZTYWBPOSTOSOHEADER() {
        return new TABLEOFZTYWBPOSTOSOHEADER();
    }

    /**
     * Create an instance of {@link ZFMWBPOSTOSOResponse }
     * 
     */
    public ZFMWBPOSTOSOResponse createZFMWBPOSTOSOResponse() {
        return new ZFMWBPOSTOSOResponse();
    }

    /**
     * Create an instance of {@link ZTYWBPOSTOSODETAIL }
     * 
     */
    public ZTYWBPOSTOSODETAIL createZTYWBPOSTOSODETAIL() {
        return new ZTYWBPOSTOSODETAIL();
    }

    /**
     * Create an instance of {@link ZTYWBPOSTOSOHEADER }
     * 
     */
    public ZTYWBPOSTOSOHEADER createZTYWBPOSTOSOHEADER() {
        return new ZTYWBPOSTOSOHEADER();
    }

}
