//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 05:42:42 PM WIB 
//


package id.co.qualitas.domain.webservice.postoso;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZTY_WB_POSTO_SO_HEADER complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZTY_WB_POSTO_SO_HEADER"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ZDOCNO" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="JDA_LOADI" type="{urn:sap-com:document:sap:rfc:functions}char100"/&gt;
 *         &lt;element name="REF_DOC" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="ZEDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="BSART" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="SI_NUMBER" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="TKNUM" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="JDA_SHDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="LGORT" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="WERKS_SOURCE" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="JDA_DEST" type="{urn:sap-com:document:sap:rfc:functions}char50"/&gt;
 *         &lt;element name="TNDR_TRKID" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="EXTI1" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="TDLNR" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="DESTN" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="DESTN_2" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="DADDR" type="{urn:sap-com:document:sap:rfc:functions}char70"/&gt;
 *         &lt;element name="TELF1" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="JDA_ARDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="VNAME" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="EMAIL" type="{urn:sap-com:document:sap:rfc:functions}char241"/&gt;
 *         &lt;element name="SI_ETD" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="ROUTE" type="{urn:sap-com:document:sap:rfc:functions}char6"/&gt;
 *         &lt;element name="VSART" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZTY_WB_POSTO_SO_HEADER", propOrder = {
    "zdocno",
    "jdaloadi",
    "refdoc",
    "zedat",
    "bsart",
    "sinumber",
    "tknum",
    "jdashdat",
    "lgort",
    "werkssource",
    "jdadest",
    "tndrtrkid",
    "exti1",
    "tdlnr",
    "destn",
    "destn2",
    "daddr",
    "telf1",
    "jdaardat",
    "vname",
    "email",
    "sietd",
    "route",
    "vsart"
})
public class ZTYWBPOSTOSOHEADER {

    @XmlElement(name = "ZDOCNO", required = true)
    protected String zdocno;
    @XmlElement(name = "JDA_LOADI", required = true)
    protected String jdaloadi;
    @XmlElement(name = "REF_DOC", required = true)
    protected String refdoc;
    @XmlElement(name = "ZEDAT", required = true)
    protected String zedat;
    @XmlElement(name = "BSART", required = true)
    protected String bsart;
    @XmlElement(name = "SI_NUMBER", required = true)
    protected String sinumber;
    @XmlElement(name = "TKNUM", required = true)
    protected String tknum;
    @XmlElement(name = "JDA_SHDAT", required = true)
    protected String jdashdat;
    @XmlElement(name = "LGORT", required = true)
    protected String lgort;
    @XmlElement(name = "WERKS_SOURCE", required = true)
    protected String werkssource;
    @XmlElement(name = "JDA_DEST", required = true)
    protected String jdadest;
    @XmlElement(name = "TNDR_TRKID", required = true)
    protected String tndrtrkid;
    @XmlElement(name = "EXTI1", required = true)
    protected String exti1;
    @XmlElement(name = "TDLNR", required = true)
    protected String tdlnr;
    @XmlElement(name = "DESTN", required = true)
    protected String destn;
    @XmlElement(name = "DESTN_2", required = true)
    protected String destn2;
    @XmlElement(name = "DADDR", required = true)
    protected String daddr;
    @XmlElement(name = "TELF1", required = true)
    protected String telf1;
    @XmlElement(name = "JDA_ARDAT", required = true)
    protected String jdaardat;
    @XmlElement(name = "VNAME", required = true)
    protected String vname;
    @XmlElement(name = "EMAIL", required = true)
    protected String email;
    @XmlElement(name = "SI_ETD", required = true)
    protected String sietd;
    @XmlElement(name = "ROUTE", required = true)
    protected String route;
    @XmlElement(name = "VSART", required = true)
    protected String vsart;

    /**
     * Gets the value of the zdocno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZDOCNO() {
        return zdocno;
    }

    /**
     * Sets the value of the zdocno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZDOCNO(String value) {
        this.zdocno = value;
    }

    /**
     * Gets the value of the jdaloadi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJDALOADI() {
        return jdaloadi;
    }

    /**
     * Sets the value of the jdaloadi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJDALOADI(String value) {
        this.jdaloadi = value;
    }

    /**
     * Gets the value of the refdoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFDOC() {
        return refdoc;
    }

    /**
     * Sets the value of the refdoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFDOC(String value) {
        this.refdoc = value;
    }

    /**
     * Gets the value of the zedat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZEDAT() {
        return zedat;
    }

    /**
     * Sets the value of the zedat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZEDAT(String value) {
        this.zedat = value;
    }

    /**
     * Gets the value of the bsart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBSART() {
        return bsart;
    }

    /**
     * Sets the value of the bsart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBSART(String value) {
        this.bsart = value;
    }

    /**
     * Gets the value of the sinumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSINUMBER() {
        return sinumber;
    }

    /**
     * Sets the value of the sinumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSINUMBER(String value) {
        this.sinumber = value;
    }

    /**
     * Gets the value of the tknum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTKNUM() {
        return tknum;
    }

    /**
     * Sets the value of the tknum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTKNUM(String value) {
        this.tknum = value;
    }

    /**
     * Gets the value of the jdashdat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJDASHDAT() {
        return jdashdat;
    }

    /**
     * Sets the value of the jdashdat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJDASHDAT(String value) {
        this.jdashdat = value;
    }

    /**
     * Gets the value of the lgort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLGORT() {
        return lgort;
    }

    /**
     * Sets the value of the lgort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLGORT(String value) {
        this.lgort = value;
    }

    /**
     * Gets the value of the werkssource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWERKSSOURCE() {
        return werkssource;
    }

    /**
     * Sets the value of the werkssource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWERKSSOURCE(String value) {
        this.werkssource = value;
    }

    /**
     * Gets the value of the jdadest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJDADEST() {
        return jdadest;
    }

    /**
     * Sets the value of the jdadest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJDADEST(String value) {
        this.jdadest = value;
    }

    /**
     * Gets the value of the tndrtrkid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTNDRTRKID() {
        return tndrtrkid;
    }

    /**
     * Sets the value of the tndrtrkid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTNDRTRKID(String value) {
        this.tndrtrkid = value;
    }

    /**
     * Gets the value of the exti1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTI1() {
        return exti1;
    }

    /**
     * Sets the value of the exti1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTI1(String value) {
        this.exti1 = value;
    }

    /**
     * Gets the value of the tdlnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDLNR() {
        return tdlnr;
    }

    /**
     * Sets the value of the tdlnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDLNR(String value) {
        this.tdlnr = value;
    }

    /**
     * Gets the value of the destn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESTN() {
        return destn;
    }

    /**
     * Sets the value of the destn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESTN(String value) {
        this.destn = value;
    }

    /**
     * Gets the value of the destn2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESTN2() {
        return destn2;
    }

    /**
     * Sets the value of the destn2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESTN2(String value) {
        this.destn2 = value;
    }

    /**
     * Gets the value of the daddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDADDR() {
        return daddr;
    }

    /**
     * Sets the value of the daddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDADDR(String value) {
        this.daddr = value;
    }

    /**
     * Gets the value of the telf1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTELF1() {
        return telf1;
    }

    /**
     * Sets the value of the telf1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTELF1(String value) {
        this.telf1 = value;
    }

    /**
     * Gets the value of the jdaardat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJDAARDAT() {
        return jdaardat;
    }

    /**
     * Sets the value of the jdaardat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJDAARDAT(String value) {
        this.jdaardat = value;
    }

    /**
     * Gets the value of the vname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVNAME() {
        return vname;
    }

    /**
     * Sets the value of the vname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVNAME(String value) {
        this.vname = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAIL() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAIL(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the sietd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIETD() {
        return sietd;
    }

    /**
     * Sets the value of the sietd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIETD(String value) {
        this.sietd = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROUTE() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROUTE(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the vsart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSART() {
        return vsart;
    }

    /**
     * Sets the value of the vsart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSART(String value) {
        this.vsart = value;
    }

}
