//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.16 at 10:11:50 AM ICT 
//


package id.co.qualitas.domain.webservice.materialtype;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.materialtype package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.materialtype
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMWBMTART }
     * 
     */
    public ZFMWBMTART createZFMWBMTART() {
        return new ZFMWBMTART();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBMTART }
     * 
     */
    public TABLEOFZTYWBMTART createTABLEOFZTYWBMTART() {
        return new TABLEOFZTYWBMTART();
    }

    /**
     * Create an instance of {@link ZFMWBMTARTResponse }
     * 
     */
    public ZFMWBMTARTResponse createZFMWBMTARTResponse() {
        return new ZFMWBMTARTResponse();
    }

    /**
     * Create an instance of {@link ZTYWBMTART }
     * 
     */
    public ZTYWBMTART createZTYWBMTART() {
        return new ZTYWBMTART();
    }

}
