//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.16 at 10:11:50 AM ICT 
//


package id.co.qualitas.domain.webservice.materialtype;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZTY_WB_MTART complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZTY_WB_MTART"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MTART" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="MTBEZ" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZTY_WB_MTART", propOrder = {
    "mtart",
    "mtbez"
})
public class ZTYWBMTART {

    @XmlElement(name = "MTART", required = true)
    protected String mtart;
    @XmlElement(name = "MTBEZ", required = true)
    protected String mtbez;

    /**
     * Gets the value of the mtart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTART() {
        return mtart;
    }

    /**
     * Sets the value of the mtart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTART(String value) {
        this.mtart = value;
    }

    /**
     * Gets the value of the mtbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTBEZ() {
        return mtbez;
    }

    /**
     * Sets the value of the mtbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTBEZ(String value) {
        this.mtbez = value;
    }

}
