//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 05:39:20 PM WIB 
//


package id.co.qualitas.domain.webservice.shipmdo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.shipmdo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.shipmdo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMWBSHIPMDO }
     * 
     */
    public ZFMWBSHIPMDO createZFMWBSHIPMDO() {
        return new ZFMWBSHIPMDO();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBSHIPMDODETAILDO }
     * 
     */
    public TABLEOFZTYWBSHIPMDODETAILDO createTABLEOFZTYWBSHIPMDODETAILDO() {
        return new TABLEOFZTYWBSHIPMDODETAILDO();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBSHIPMDODETAILITEMDO }
     * 
     */
    public TABLEOFZTYWBSHIPMDODETAILITEMDO createTABLEOFZTYWBSHIPMDODETAILITEMDO() {
        return new TABLEOFZTYWBSHIPMDODETAILITEMDO();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBSHIPMDOSHIPMENT }
     * 
     */
    public TABLEOFZTYWBSHIPMDOSHIPMENT createTABLEOFZTYWBSHIPMDOSHIPMENT() {
        return new TABLEOFZTYWBSHIPMDOSHIPMENT();
    }

    /**
     * Create an instance of {@link ZFMWBSHIPMDOResponse }
     * 
     */
    public ZFMWBSHIPMDOResponse createZFMWBSHIPMDOResponse() {
        return new ZFMWBSHIPMDOResponse();
    }

    /**
     * Create an instance of {@link ZTYWBSHIPMDODETAILDO }
     * 
     */
    public ZTYWBSHIPMDODETAILDO createZTYWBSHIPMDODETAILDO() {
        return new ZTYWBSHIPMDODETAILDO();
    }

    /**
     * Create an instance of {@link ZTYWBSHIPMDODETAILITEMDO }
     * 
     */
    public ZTYWBSHIPMDODETAILITEMDO createZTYWBSHIPMDODETAILITEMDO() {
        return new ZTYWBSHIPMDODETAILITEMDO();
    }

    /**
     * Create an instance of {@link ZTYWBSHIPMDOSHIPMENT }
     * 
     */
    public ZTYWBSHIPMDOSHIPMENT createZTYWBSHIPMDOSHIPMENT() {
        return new ZTYWBSHIPMDOSHIPMENT();
    }

}
