//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 05:39:20 PM WIB 
//


package id.co.qualitas.domain.webservice.shipmdo;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZTY_WB_SHIPM_DO_DETAIL_DO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZTY_WB_SHIPM_DO_DETAIL_DO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ZDOCNO" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="VBELN" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="LFDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="LGORT" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="WERKS" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="TKNUM" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="T_WEIGHT" type="{urn:sap-com:document:sap:rfc:functions}quantum15.3"/&gt;
 *         &lt;element name="W_UOM" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="T_VOLUM" type="{urn:sap-com:document:sap:rfc:functions}quantum15.3"/&gt;
 *         &lt;element name="V_UOM" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZTY_WB_SHIPM_DO_DETAIL_DO", propOrder = {
    "zdocno",
    "vbeln",
    "lfdat",
    "lgort",
    "werks",
    "tknum",
    "tweight",
    "wuom",
    "tvolum",
    "vuom"
})
public class ZTYWBSHIPMDODETAILDO {

    @XmlElement(name = "ZDOCNO", required = true)
    protected String zdocno;
    @XmlElement(name = "VBELN", required = true)
    protected String vbeln;
    @XmlElement(name = "LFDAT", required = true)
    protected String lfdat;
    @XmlElement(name = "LGORT", required = true)
    protected String lgort;
    @XmlElement(name = "WERKS", required = true)
    protected String werks;
    @XmlElement(name = "TKNUM", required = true)
    protected String tknum;
    @XmlElement(name = "T_WEIGHT", required = true)
    protected BigDecimal tweight;
    @XmlElement(name = "W_UOM", required = true)
    protected String wuom;
    @XmlElement(name = "T_VOLUM", required = true)
    protected BigDecimal tvolum;
    @XmlElement(name = "V_UOM", required = true)
    protected String vuom;

    /**
     * Gets the value of the zdocno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZDOCNO() {
        return zdocno;
    }

    /**
     * Sets the value of the zdocno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZDOCNO(String value) {
        this.zdocno = value;
    }

    /**
     * Gets the value of the vbeln property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVBELN() {
        return vbeln;
    }

    /**
     * Sets the value of the vbeln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVBELN(String value) {
        this.vbeln = value;
    }

    /**
     * Gets the value of the lfdat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLFDAT() {
        return lfdat;
    }

    /**
     * Sets the value of the lfdat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLFDAT(String value) {
        this.lfdat = value;
    }

    /**
     * Gets the value of the lgort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLGORT() {
        return lgort;
    }

    /**
     * Sets the value of the lgort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLGORT(String value) {
        this.lgort = value;
    }

    /**
     * Gets the value of the werks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWERKS() {
        return werks;
    }

    /**
     * Sets the value of the werks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWERKS(String value) {
        this.werks = value;
    }

    /**
     * Gets the value of the tknum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTKNUM() {
        return tknum;
    }

    /**
     * Sets the value of the tknum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTKNUM(String value) {
        this.tknum = value;
    }

    /**
     * Gets the value of the tweight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTWEIGHT() {
        return tweight;
    }

    /**
     * Sets the value of the tweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTWEIGHT(BigDecimal value) {
        this.tweight = value;
    }

    /**
     * Gets the value of the wuom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWUOM() {
        return wuom;
    }

    /**
     * Sets the value of the wuom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWUOM(String value) {
        this.wuom = value;
    }

    /**
     * Gets the value of the tvolum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTVOLUM() {
        return tvolum;
    }

    /**
     * Sets the value of the tvolum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTVOLUM(BigDecimal value) {
        this.tvolum = value;
    }

    /**
     * Gets the value of the vuom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVUOM() {
        return vuom;
    }

    /**
     * Sets the value of the vuom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVUOM(String value) {
        this.vuom = value;
    }

}
