//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 02:39:17 PM WIB 
//


package id.co.qualitas.domain.webservice.createdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIDELICIOUSCREATEDITEMS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIDELICIOUSCREATEDITEMS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DOCUMENT_CATEGORY_SD" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="DOCUMENT_NUMB" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="DOCUMENT_ITEM" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="QUANTITY_SALES_UOM" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="SALES_UNIT" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="MATERIAL" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIDELICIOUSCREATEDITEMS", propOrder = {
    "id",
    "documentcategorysd",
    "documentnumb",
    "documentitem",
    "quantitysalesuom",
    "salesunit",
    "material"
})
public class BAPIDELICIOUSCREATEDITEMS {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "DOCUMENT_CATEGORY_SD", required = true)
    protected String documentcategorysd;
    @XmlElement(name = "DOCUMENT_NUMB", required = true)
    protected String documentnumb;
    @XmlElement(name = "DOCUMENT_ITEM", required = true)
    protected String documentitem;
    @XmlElement(name = "QUANTITY_SALES_UOM")
    protected float quantitysalesuom;
    @XmlElement(name = "SALES_UNIT", required = true)
    protected String salesunit;
    @XmlElement(name = "MATERIAL", required = true)
    protected String material;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the documentcategorysd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCUMENTCATEGORYSD() {
        return documentcategorysd;
    }

    /**
     * Sets the value of the documentcategorysd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCUMENTCATEGORYSD(String value) {
        this.documentcategorysd = value;
    }

    /**
     * Gets the value of the documentnumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCUMENTNUMB() {
        return documentnumb;
    }

    /**
     * Sets the value of the documentnumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCUMENTNUMB(String value) {
        this.documentnumb = value;
    }

    /**
     * Gets the value of the documentitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCUMENTITEM() {
        return documentitem;
    }

    /**
     * Sets the value of the documentitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCUMENTITEM(String value) {
        this.documentitem = value;
    }

    /**
     * Gets the value of the quantitysalesuom property.
     * 
     */
    public float getQUANTITYSALESUOM() {
        return quantitysalesuom;
    }

    /**
     * Sets the value of the quantitysalesuom property.
     * 
     */
    public void setQUANTITYSALESUOM(float value) {
        this.quantitysalesuom = value;
    }

    /**
     * Gets the value of the salesunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSALESUNIT() {
        return salesunit;
    }

    /**
     * Sets the value of the salesunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSALESUNIT(String value) {
        this.salesunit = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATERIAL() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATERIAL(String value) {
        this.material = value;
    }

}
