//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 02:39:17 PM WIB 
//


package id.co.qualitas.domain.webservice.createdo;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIDLVREFTOSALESORDER complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIDLVREFTOSALESORDER"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="REF_DOC" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="REF_ITEM" type="{urn:sap-com:document:sap:rfc:functions}numeric6"/&gt;
 *         &lt;element name="DLV_QTY" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="SALES_UNIT" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="SALES_UNIT_ISO" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="DELIV_NUMB" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIDLVREFTOSALESORDER", propOrder = {
    "refdoc",
    "refitem",
    "dlvqty",
    "salesunit",
    "salesunitiso",
    "delivnumb"
})
public class BAPIDLVREFTOSALESORDER {

    @XmlElement(name = "REF_DOC", required = true)
    protected String refdoc;
    @XmlElement(name = "REF_ITEM", required = true)
    protected String refitem;
    @XmlElement(name = "DLV_QTY", required = true)
    protected BigDecimal dlvqty;
    @XmlElement(name = "SALES_UNIT", required = true)
    protected String salesunit;
    @XmlElement(name = "SALES_UNIT_ISO", required = true)
    protected String salesunitiso;
    @XmlElement(name = "DELIV_NUMB", required = true)
    protected String delivnumb;

    /**
     * Gets the value of the refdoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFDOC() {
        return refdoc;
    }

    /**
     * Sets the value of the refdoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFDOC(String value) {
        this.refdoc = value;
    }

    /**
     * Gets the value of the refitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFITEM() {
        return refitem;
    }

    /**
     * Sets the value of the refitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFITEM(String value) {
        this.refitem = value;
    }

    /**
     * Gets the value of the dlvqty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDLVQTY() {
        return dlvqty;
    }

    /**
     * Sets the value of the dlvqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDLVQTY(BigDecimal value) {
        this.dlvqty = value;
    }

    /**
     * Gets the value of the salesunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSALESUNIT() {
        return salesunit;
    }

    /**
     * Sets the value of the salesunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSALESUNIT(String value) {
        this.salesunit = value;
    }

    /**
     * Gets the value of the salesunitiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSALESUNITISO() {
        return salesunitiso;
    }

    /**
     * Sets the value of the salesunitiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSALESUNITISO(String value) {
        this.salesunitiso = value;
    }

    /**
     * Gets the value of the delivnumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVNUMB() {
        return delivnumb;
    }

    /**
     * Sets the value of the delivnumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVNUMB(String value) {
        this.delivnumb = value;
    }

}
