//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 02:39:17 PM WIB 
//


package id.co.qualitas.domain.webservice.createdo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.qualitas.domain.webservice.createdo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.qualitas.domain.webservice.createdo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZFMWBCREATEDO }
     * 
     */
    public ZFMWBCREATEDO createZFMWBCREATEDO() {
        return new ZFMWBCREATEDO();
    }

    /**
     * Create an instance of {@link TABLEOFBAPIDELICIOUSCREATEDITEMS }
     * 
     */
    public TABLEOFBAPIDELICIOUSCREATEDITEMS createTABLEOFBAPIDELICIOUSCREATEDITEMS() {
        return new TABLEOFBAPIDELICIOUSCREATEDITEMS();
    }

    /**
     * Create an instance of {@link TABLEOFBAPISHPDELIVNUMB }
     * 
     */
    public TABLEOFBAPISHPDELIVNUMB createTABLEOFBAPISHPDELIVNUMB() {
        return new TABLEOFBAPISHPDELIVNUMB();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBCREATEDODETAIL }
     * 
     */
    public TABLEOFZTYWBCREATEDODETAIL createTABLEOFZTYWBCREATEDODETAIL() {
        return new TABLEOFZTYWBCREATEDODETAIL();
    }

    /**
     * Create an instance of {@link ZTYWBCREATEDOHEADER }
     * 
     */
    public ZTYWBCREATEDOHEADER createZTYWBCREATEDOHEADER() {
        return new ZTYWBCREATEDOHEADER();
    }

    /**
     * Create an instance of {@link TABLEOFBAPIDLVREFTOSALESORDER }
     * 
     */
    public TABLEOFBAPIDLVREFTOSALESORDER createTABLEOFBAPIDLVREFTOSALESORDER() {
        return new TABLEOFBAPIDLVREFTOSALESORDER();
    }

    /**
     * Create an instance of {@link TABLEOFBAPIDELICIOUSREQUEST }
     * 
     */
    public TABLEOFBAPIDELICIOUSREQUEST createTABLEOFBAPIDELICIOUSREQUEST() {
        return new TABLEOFBAPIDELICIOUSREQUEST();
    }

    /**
     * Create an instance of {@link TABLEOFBAPIRET2 }
     * 
     */
    public TABLEOFBAPIRET2 createTABLEOFBAPIRET2() {
        return new TABLEOFBAPIRET2();
    }

    /**
     * Create an instance of {@link THEAD }
     * 
     */
    public THEAD createTHEAD() {
        return new THEAD();
    }

    /**
     * Create an instance of {@link TABLEOFTLINE }
     * 
     */
    public TABLEOFTLINE createTABLEOFTLINE() {
        return new TABLEOFTLINE();
    }

    /**
     * Create an instance of {@link TABLEOFZTYWBCREATEDOWEIGHT }
     * 
     */
    public TABLEOFZTYWBCREATEDOWEIGHT createTABLEOFZTYWBCREATEDOWEIGHT() {
        return new TABLEOFZTYWBCREATEDOWEIGHT();
    }

    /**
     * Create an instance of {@link ZFMWBCREATEDOResponse }
     * 
     */
    public ZFMWBCREATEDOResponse createZFMWBCREATEDOResponse() {
        return new ZFMWBCREATEDOResponse();
    }

    /**
     * Create an instance of {@link BAPIDELICIOUSCREATEDITEMS }
     * 
     */
    public BAPIDELICIOUSCREATEDITEMS createBAPIDELICIOUSCREATEDITEMS() {
        return new BAPIDELICIOUSCREATEDITEMS();
    }

    /**
     * Create an instance of {@link ZTYWBCREATEDODETAIL }
     * 
     */
    public ZTYWBCREATEDODETAIL createZTYWBCREATEDODETAIL() {
        return new ZTYWBCREATEDODETAIL();
    }

    /**
     * Create an instance of {@link BAPIDELICIOUSREQUEST }
     * 
     */
    public BAPIDELICIOUSREQUEST createBAPIDELICIOUSREQUEST() {
        return new BAPIDELICIOUSREQUEST();
    }

    /**
     * Create an instance of {@link BAPIRET2 }
     * 
     */
    public BAPIRET2 createBAPIRET2() {
        return new BAPIRET2();
    }

    /**
     * Create an instance of {@link ZTYWBCREATEDOWEIGHT }
     * 
     */
    public ZTYWBCREATEDOWEIGHT createZTYWBCREATEDOWEIGHT() {
        return new ZTYWBCREATEDOWEIGHT();
    }

    /**
     * Create an instance of {@link TLINE }
     * 
     */
    public TLINE createTLINE() {
        return new TLINE();
    }

    /**
     * Create an instance of {@link BAPIDLVREFTOSALESORDER }
     * 
     */
    public BAPIDLVREFTOSALESORDER createBAPIDLVREFTOSALESORDER() {
        return new BAPIDLVREFTOSALESORDER();
    }

    /**
     * Create an instance of {@link BAPISHPDELIVNUMB }
     * 
     */
    public BAPISHPDELIVNUMB createBAPISHPDELIVNUMB() {
        return new BAPISHPDELIVNUMB();
    }

}
