//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 02:39:17 PM WIB 
//


package id.co.qualitas.domain.webservice.createdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for THEAD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="THEAD"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TDOBJECT" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="TDNAME" type="{urn:sap-com:document:sap:rfc:functions}char70"/&gt;
 *         &lt;element name="TDID" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="TDSPRAS" type="{urn:sap-com:document:sap:rfc:functions}lang"/&gt;
 *         &lt;element name="TDTITLE" type="{urn:sap-com:document:sap:rfc:functions}char50"/&gt;
 *         &lt;element name="TDFORM" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="TDSTYLE" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="TDVERSION" type="{urn:sap-com:document:sap:rfc:functions}numeric5"/&gt;
 *         &lt;element name="TDFUSER" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="TDFRELES" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="TDFDATE" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="TDFTIME" type="{urn:sap-com:document:sap:rfc:functions}time"/&gt;
 *         &lt;element name="TDLUSER" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="TDLRELES" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="TDLDATE" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="TDLTIME" type="{urn:sap-com:document:sap:rfc:functions}time"/&gt;
 *         &lt;element name="TDLINESIZE" type="{urn:sap-com:document:sap:rfc:functions}numeric3"/&gt;
 *         &lt;element name="TDTXTLINES" type="{urn:sap-com:document:sap:rfc:functions}numeric5"/&gt;
 *         &lt;element name="TDHYPHENAT" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="TDOSPRAS" type="{urn:sap-com:document:sap:rfc:functions}lang"/&gt;
 *         &lt;element name="TDTRANSTAT" type="{urn:sap-com:document:sap:rfc:functions}numeric1"/&gt;
 *         &lt;element name="TDMACODE1" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="TDMACODE2" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="TDREFOBJ" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="TDREFNAME" type="{urn:sap-com:document:sap:rfc:functions}char70"/&gt;
 *         &lt;element name="TDREFID" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="TDTEXTTYPE" type="{urn:sap-com:document:sap:rfc:functions}char6"/&gt;
 *         &lt;element name="TDCOMPRESS" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="MANDT" type="{urn:sap-com:document:sap:rfc:functions}clnt3"/&gt;
 *         &lt;element name="TDOCLASS" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="LOGSYS" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "THEAD", propOrder = {
    "tdobject",
    "tdname",
    "tdid",
    "tdspras",
    "tdtitle",
    "tdform",
    "tdstyle",
    "tdversion",
    "tdfuser",
    "tdfreles",
    "tdfdate",
    "tdftime",
    "tdluser",
    "tdlreles",
    "tdldate",
    "tdltime",
    "tdlinesize",
    "tdtxtlines",
    "tdhyphenat",
    "tdospras",
    "tdtranstat",
    "tdmacode1",
    "tdmacode2",
    "tdrefobj",
    "tdrefname",
    "tdrefid",
    "tdtexttype",
    "tdcompress",
    "mandt",
    "tdoclass",
    "logsys"
})
public class THEAD {

    @XmlElement(name = "TDOBJECT", required = true)
    protected String tdobject;
    @XmlElement(name = "TDNAME", required = true)
    protected String tdname;
    @XmlElement(name = "TDID", required = true)
    protected String tdid;
    @XmlElement(name = "TDSPRAS", required = true)
    protected String tdspras;
    @XmlElement(name = "TDTITLE", required = true)
    protected String tdtitle;
    @XmlElement(name = "TDFORM", required = true)
    protected String tdform;
    @XmlElement(name = "TDSTYLE", required = true)
    protected String tdstyle;
    @XmlElement(name = "TDVERSION", required = true)
    protected String tdversion;
    @XmlElement(name = "TDFUSER", required = true)
    protected String tdfuser;
    @XmlElement(name = "TDFRELES", required = true)
    protected String tdfreles;
    @XmlElement(name = "TDFDATE", required = true)
    protected String tdfdate;
    @XmlElement(name = "TDFTIME", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar tdftime;
    @XmlElement(name = "TDLUSER", required = true)
    protected String tdluser;
    @XmlElement(name = "TDLRELES", required = true)
    protected String tdlreles;
    @XmlElement(name = "TDLDATE", required = true)
    protected String tdldate;
    @XmlElement(name = "TDLTIME", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar tdltime;
    @XmlElement(name = "TDLINESIZE", required = true)
    protected String tdlinesize;
    @XmlElement(name = "TDTXTLINES", required = true)
    protected String tdtxtlines;
    @XmlElement(name = "TDHYPHENAT", required = true)
    protected String tdhyphenat;
    @XmlElement(name = "TDOSPRAS", required = true)
    protected String tdospras;
    @XmlElement(name = "TDTRANSTAT", required = true)
    protected String tdtranstat;
    @XmlElement(name = "TDMACODE1", required = true)
    protected String tdmacode1;
    @XmlElement(name = "TDMACODE2", required = true)
    protected String tdmacode2;
    @XmlElement(name = "TDREFOBJ", required = true)
    protected String tdrefobj;
    @XmlElement(name = "TDREFNAME", required = true)
    protected String tdrefname;
    @XmlElement(name = "TDREFID", required = true)
    protected String tdrefid;
    @XmlElement(name = "TDTEXTTYPE", required = true)
    protected String tdtexttype;
    @XmlElement(name = "TDCOMPRESS", required = true)
    protected String tdcompress;
    @XmlElement(name = "MANDT", required = true)
    protected String mandt;
    @XmlElement(name = "TDOCLASS", required = true)
    protected String tdoclass;
    @XmlElement(name = "LOGSYS", required = true)
    protected String logsys;

    /**
     * Gets the value of the tdobject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDOBJECT() {
        return tdobject;
    }

    /**
     * Sets the value of the tdobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDOBJECT(String value) {
        this.tdobject = value;
    }

    /**
     * Gets the value of the tdname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDNAME() {
        return tdname;
    }

    /**
     * Sets the value of the tdname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDNAME(String value) {
        this.tdname = value;
    }

    /**
     * Gets the value of the tdid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDID() {
        return tdid;
    }

    /**
     * Sets the value of the tdid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDID(String value) {
        this.tdid = value;
    }

    /**
     * Gets the value of the tdspras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDSPRAS() {
        return tdspras;
    }

    /**
     * Sets the value of the tdspras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDSPRAS(String value) {
        this.tdspras = value;
    }

    /**
     * Gets the value of the tdtitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDTITLE() {
        return tdtitle;
    }

    /**
     * Sets the value of the tdtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDTITLE(String value) {
        this.tdtitle = value;
    }

    /**
     * Gets the value of the tdform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDFORM() {
        return tdform;
    }

    /**
     * Sets the value of the tdform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDFORM(String value) {
        this.tdform = value;
    }

    /**
     * Gets the value of the tdstyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDSTYLE() {
        return tdstyle;
    }

    /**
     * Sets the value of the tdstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDSTYLE(String value) {
        this.tdstyle = value;
    }

    /**
     * Gets the value of the tdversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDVERSION() {
        return tdversion;
    }

    /**
     * Sets the value of the tdversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDVERSION(String value) {
        this.tdversion = value;
    }

    /**
     * Gets the value of the tdfuser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDFUSER() {
        return tdfuser;
    }

    /**
     * Sets the value of the tdfuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDFUSER(String value) {
        this.tdfuser = value;
    }

    /**
     * Gets the value of the tdfreles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDFRELES() {
        return tdfreles;
    }

    /**
     * Sets the value of the tdfreles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDFRELES(String value) {
        this.tdfreles = value;
    }

    /**
     * Gets the value of the tdfdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDFDATE() {
        return tdfdate;
    }

    /**
     * Sets the value of the tdfdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDFDATE(String value) {
        this.tdfdate = value;
    }

    /**
     * Gets the value of the tdftime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTDFTIME() {
        return tdftime;
    }

    /**
     * Sets the value of the tdftime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTDFTIME(XMLGregorianCalendar value) {
        this.tdftime = value;
    }

    /**
     * Gets the value of the tdluser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDLUSER() {
        return tdluser;
    }

    /**
     * Sets the value of the tdluser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDLUSER(String value) {
        this.tdluser = value;
    }

    /**
     * Gets the value of the tdlreles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDLRELES() {
        return tdlreles;
    }

    /**
     * Sets the value of the tdlreles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDLRELES(String value) {
        this.tdlreles = value;
    }

    /**
     * Gets the value of the tdldate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDLDATE() {
        return tdldate;
    }

    /**
     * Sets the value of the tdldate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDLDATE(String value) {
        this.tdldate = value;
    }

    /**
     * Gets the value of the tdltime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTDLTIME() {
        return tdltime;
    }

    /**
     * Sets the value of the tdltime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTDLTIME(XMLGregorianCalendar value) {
        this.tdltime = value;
    }

    /**
     * Gets the value of the tdlinesize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDLINESIZE() {
        return tdlinesize;
    }

    /**
     * Sets the value of the tdlinesize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDLINESIZE(String value) {
        this.tdlinesize = value;
    }

    /**
     * Gets the value of the tdtxtlines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDTXTLINES() {
        return tdtxtlines;
    }

    /**
     * Sets the value of the tdtxtlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDTXTLINES(String value) {
        this.tdtxtlines = value;
    }

    /**
     * Gets the value of the tdhyphenat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDHYPHENAT() {
        return tdhyphenat;
    }

    /**
     * Sets the value of the tdhyphenat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDHYPHENAT(String value) {
        this.tdhyphenat = value;
    }

    /**
     * Gets the value of the tdospras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDOSPRAS() {
        return tdospras;
    }

    /**
     * Sets the value of the tdospras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDOSPRAS(String value) {
        this.tdospras = value;
    }

    /**
     * Gets the value of the tdtranstat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDTRANSTAT() {
        return tdtranstat;
    }

    /**
     * Sets the value of the tdtranstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDTRANSTAT(String value) {
        this.tdtranstat = value;
    }

    /**
     * Gets the value of the tdmacode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDMACODE1() {
        return tdmacode1;
    }

    /**
     * Sets the value of the tdmacode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDMACODE1(String value) {
        this.tdmacode1 = value;
    }

    /**
     * Gets the value of the tdmacode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDMACODE2() {
        return tdmacode2;
    }

    /**
     * Sets the value of the tdmacode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDMACODE2(String value) {
        this.tdmacode2 = value;
    }

    /**
     * Gets the value of the tdrefobj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDREFOBJ() {
        return tdrefobj;
    }

    /**
     * Sets the value of the tdrefobj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDREFOBJ(String value) {
        this.tdrefobj = value;
    }

    /**
     * Gets the value of the tdrefname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDREFNAME() {
        return tdrefname;
    }

    /**
     * Sets the value of the tdrefname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDREFNAME(String value) {
        this.tdrefname = value;
    }

    /**
     * Gets the value of the tdrefid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDREFID() {
        return tdrefid;
    }

    /**
     * Sets the value of the tdrefid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDREFID(String value) {
        this.tdrefid = value;
    }

    /**
     * Gets the value of the tdtexttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDTEXTTYPE() {
        return tdtexttype;
    }

    /**
     * Sets the value of the tdtexttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDTEXTTYPE(String value) {
        this.tdtexttype = value;
    }

    /**
     * Gets the value of the tdcompress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDCOMPRESS() {
        return tdcompress;
    }

    /**
     * Sets the value of the tdcompress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDCOMPRESS(String value) {
        this.tdcompress = value;
    }

    /**
     * Gets the value of the mandt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMANDT() {
        return mandt;
    }

    /**
     * Sets the value of the mandt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMANDT(String value) {
        this.mandt = value;
    }

    /**
     * Gets the value of the tdoclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDOCLASS() {
        return tdoclass;
    }

    /**
     * Sets the value of the tdoclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDOCLASS(String value) {
        this.tdoclass = value;
    }

    /**
     * Gets the value of the logsys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOGSYS() {
        return logsys;
    }

    /**
     * Sets the value of the logsys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOGSYS(String value) {
        this.logsys = value;
    }

}
