//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 02:39:17 PM WIB 
//


package id.co.qualitas.domain.webservice.createdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BDC_MESSAGE" type="{urn:sap-com:document:sap:rfc:functions}char255"/&gt;
 *         &lt;element name="CREATEDITEMS" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIDELICIOUSCREATEDITEMS" minOccurs="0"/&gt;
 *         &lt;element name="DELIVERIES" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPISHPDELIVNUMB" minOccurs="0"/&gt;
 *         &lt;element name="DETAIL_BATCH" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZTY_WB_CREATE_DO_DETAIL" minOccurs="0"/&gt;
 *         &lt;element name="ITEMS" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIDLVREFTOSALESORDER" minOccurs="0"/&gt;
 *         &lt;element name="REQUEST" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIDELICIOUSREQUEST" minOccurs="0"/&gt;
 *         &lt;element name="RETURN_SOBU" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIRET2"/&gt;
 *         &lt;element name="RETURN_STO" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIRET2" minOccurs="0"/&gt;
 *         &lt;element name="TEXT_LINES" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_TLINE" minOccurs="0"/&gt;
 *         &lt;element name="WEIGHT" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZTY_WB_CREATE_DO_WEIGHT" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bdcmessage",
    "createditems",
    "deliveries",
    "detailbatch",
    "items",
    "request",
    "returnsobu",
    "returnsto",
    "textlines",
    "weight"
})
@XmlRootElement(name = "ZFM_WB_CREATE_DOResponse")
public class ZFMWBCREATEDOResponse {

    @XmlElement(name = "BDC_MESSAGE", required = true)
    protected String bdcmessage;
    @XmlElement(name = "CREATEDITEMS")
    protected TABLEOFBAPIDELICIOUSCREATEDITEMS createditems;
    @XmlElement(name = "DELIVERIES")
    protected TABLEOFBAPISHPDELIVNUMB deliveries;
    @XmlElement(name = "DETAIL_BATCH")
    protected TABLEOFZTYWBCREATEDODETAIL detailbatch;
    @XmlElement(name = "ITEMS")
    protected TABLEOFBAPIDLVREFTOSALESORDER items;
    @XmlElement(name = "REQUEST")
    protected TABLEOFBAPIDELICIOUSREQUEST request;
    @XmlElement(name = "RETURN_SOBU", required = true)
    protected TABLEOFBAPIRET2 returnsobu;
    @XmlElement(name = "RETURN_STO")
    protected TABLEOFBAPIRET2 returnsto;
    @XmlElement(name = "TEXT_LINES")
    protected TABLEOFTLINE textlines;
    @XmlElement(name = "WEIGHT")
    protected TABLEOFZTYWBCREATEDOWEIGHT weight;

    /**
     * Gets the value of the bdcmessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBDCMESSAGE() {
        return bdcmessage;
    }

    /**
     * Sets the value of the bdcmessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBDCMESSAGE(String value) {
        this.bdcmessage = value;
    }

    /**
     * Gets the value of the createditems property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIDELICIOUSCREATEDITEMS }
     *     
     */
    public TABLEOFBAPIDELICIOUSCREATEDITEMS getCREATEDITEMS() {
        return createditems;
    }

    /**
     * Sets the value of the createditems property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIDELICIOUSCREATEDITEMS }
     *     
     */
    public void setCREATEDITEMS(TABLEOFBAPIDELICIOUSCREATEDITEMS value) {
        this.createditems = value;
    }

    /**
     * Gets the value of the deliveries property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPISHPDELIVNUMB }
     *     
     */
    public TABLEOFBAPISHPDELIVNUMB getDELIVERIES() {
        return deliveries;
    }

    /**
     * Sets the value of the deliveries property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPISHPDELIVNUMB }
     *     
     */
    public void setDELIVERIES(TABLEOFBAPISHPDELIVNUMB value) {
        this.deliveries = value;
    }

    /**
     * Gets the value of the detailbatch property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZTYWBCREATEDODETAIL }
     *     
     */
    public TABLEOFZTYWBCREATEDODETAIL getDETAILBATCH() {
        return detailbatch;
    }

    /**
     * Sets the value of the detailbatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZTYWBCREATEDODETAIL }
     *     
     */
    public void setDETAILBATCH(TABLEOFZTYWBCREATEDODETAIL value) {
        this.detailbatch = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIDLVREFTOSALESORDER }
     *     
     */
    public TABLEOFBAPIDLVREFTOSALESORDER getITEMS() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIDLVREFTOSALESORDER }
     *     
     */
    public void setITEMS(TABLEOFBAPIDLVREFTOSALESORDER value) {
        this.items = value;
    }

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIDELICIOUSREQUEST }
     *     
     */
    public TABLEOFBAPIDELICIOUSREQUEST getREQUEST() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIDELICIOUSREQUEST }
     *     
     */
    public void setREQUEST(TABLEOFBAPIDELICIOUSREQUEST value) {
        this.request = value;
    }

    /**
     * Gets the value of the returnsobu property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public TABLEOFBAPIRET2 getRETURNSOBU() {
        return returnsobu;
    }

    /**
     * Sets the value of the returnsobu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public void setRETURNSOBU(TABLEOFBAPIRET2 value) {
        this.returnsobu = value;
    }

    /**
     * Gets the value of the returnsto property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public TABLEOFBAPIRET2 getRETURNSTO() {
        return returnsto;
    }

    /**
     * Sets the value of the returnsto property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public void setRETURNSTO(TABLEOFBAPIRET2 value) {
        this.returnsto = value;
    }

    /**
     * Gets the value of the textlines property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFTLINE }
     *     
     */
    public TABLEOFTLINE getTEXTLINES() {
        return textlines;
    }

    /**
     * Sets the value of the textlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFTLINE }
     *     
     */
    public void setTEXTLINES(TABLEOFTLINE value) {
        this.textlines = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZTYWBCREATEDOWEIGHT }
     *     
     */
    public TABLEOFZTYWBCREATEDOWEIGHT getWEIGHT() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZTYWBCREATEDOWEIGHT }
     *     
     */
    public void setWEIGHT(TABLEOFZTYWBCREATEDOWEIGHT value) {
        this.weight = value;
    }

}
